/**
 * @license MIT
 */
(function(){var e,q=this,aa=q.URL||q.webkitURL,ba=q.WebKitBlobBuilder,ca=q.webkitAudioContext||q.AudioContext;function da(){}function ea(){}function r(a,b){a.B=b.prototype;a.prototype=Object.create(b.prototype)}function t(a,b,c,d){var f=q;a=a.split(".");for(var g=a.length-1,h=0;h<g;++h){var k=a[h];f[k]||(f[k]={});f=f[k]}f[a[g]]=b;for(var l in c)b.prototype[l]=c[l];b.prototype.initialize=b;if(d)for(l in d)b[l]=d[l]}
function fa(a,b){for(var c=q,d=a.split("."),f=d.length,g=0;g<f;++g){var h=d[g];c[h]||(c[h]={});c=c[h]}for(var k in b)c[k]=b[k];return c}function ga(a){return"string"==typeof a}function ha(a){return 0<a?a:-a}function u(a,b){return a<b?a:b}function z(a,b){return a>b?a:b}function ia(){return document.createElement("canvas")}function A(a){return new Float32Array(a)}fa("createjs",{version:"0.7.1",denaVersion:9});function ja(){}ja.prototype.clone=function(){return null};var ma={},na=-1,oa=0,pa=0,qa=!1;function ra(a,b){if(b&2){if("touchstart"==a.type){var c=a.timeStamp-pa;qa=c<oa;qa||(pa=a.timeStamp);return qa}if("touchend"==a.type||"touchmove"==a.type)return qa}else if(b&4){if("pointerdown"==a.type)return c=a.timeStamp-pa,qa=c<oa,qa||(pa=a.timeStamp),qa;if("pointerup"==a.type||"pointermove"==a.type)return qa}if(b&1){if("mousedown"==a.type)return c=a.timeStamp-pa,qa=c<oa,qa||(pa=a.timeStamp),qa;if("mouseup"==a.type||"mousemove"==a.type)return qa}return!1}
fa("createjs.Config",{clearCache:function(){},setCacheVersion:function(){},setUseAndroidWorkarounds:function(a,b){ma[a]=b|0},setEventInterval:function(a){oa=a}});function B(a){this.e=a}r(B,ja);B.prototype.e="";B.prototype.target=null;B.prototype.currentTarget=null;e=B.prototype;e.Na=!1;e.Dc=!1;e.Yd=!1;e.Ue=!1;e.Td=null;B.prototype.preventDefault=function(){this.Dc=!0};B.prototype.stopPropagation=function(){this.Yd=!0};B.prototype.remove=function(){this.Ue=!0};B.prototype.addEventListener=function(a,b){return this.Td.Jb(a,b)};B.prototype.removeEventListener=function(a,b){this.Td.Ib(a,b)};function C(){}r(C,ja);function sa(a){return{click:1,mousedown:2,pressmove:4,pressup:8}[a]||0}function ta(a,b,c,d){this.g=a.handleEvent||a;this.e=a.handleEvent?a:b;this.h=c;this.Db=d}function ua(a){this.g=[a];this.e=null;this.h=!1}function va(a){if(!a.h)return a.g;a.e||(a.e=a.g.slice());return a.e}C.prototype.parent=null;e=C.prototype;e.aa=null;e.Ya=0;e.Ge=!1;e.lc=null;
function wa(a,b){if(a.aa){var c=a.aa[b.e];if(c&&c.g.length)if(b.target=a,b.currentTarget=a,b.Td=a,a.Ge)a.lc=a.lc||[],a.lc.push(b);else{a.Ge=!0;var d;c.h=!0;d=c.g;for(var f=d.length,g=0;g<f;++g){b.Ue=!1;var h=d[g],k=h,l=b;k.g.call(k.e,l,k.Db);if(l.Ue||k.h)for(k=c,k.e||(k.e=k.g.slice()),k=k.e,l=k.length-1;0<=l;--l)if(k[l]===h){k.splice(l,1);break}}c.h=!1;c.e&&(c.g=c.e,c.e=null);for(a.Ge=!1;a.lc;)for(c=a.lc,a.lc=null,g=0;g<c.length;++g)wa(a,c[g])}}}
function D(a,b){wa(a,b);if(b.Na&&a.parent)for(var c=a.parent;c&&!b.Yd;c=c.parent)wa(c,b);b.target=null;b.currentTarget=null;b.Td=null;return b.Dc}function xa(a,b){var c=a.aa;return c&&c[b]?D(a,new B(b)):!1}e.rh=function(a,b,c){return this.Jb(a,b,q,!1,null,c)};e.Jb=function(a,b,c,d,f,g){b&&!g&&(c=new ta(b,c||this,d||!1,f||null),this.aa||(this.aa={}),(d=this.aa[a])?va(d).push(c):this.aa[a]=new ua(c),this.Ya|=sa(a));return b};
e.Ib=function(a,b,c){if(b&&!c&&this.aa&&(c=this.aa[a])){c=va(c);for(var d=c.length-1;0<=d;--d){var f=c[d];if(b.handleEvent?f.e===b:f.g===b){c.splice(d,1);break}}!c.length&&(a=sa(a))&&(this.Ya&=~a)}};e.Pb=function(a){a?this.aa&&this.aa[a]&&(this.aa[a]=null):this.aa=null};e.re=function(a){return ga(a)?xa(this,a):D(this,new B(a.type))};e.ba=function(a){return this.aa&&(a=this.aa[a])&&a.g.length?!0:!1};e.aj=function(a){for(var b=this;b;){if(b.ba(a))return!0;b=b.parent}return!1};
e.contains=function(a){for(;a;){if(a===this)return!0;a=a.parent}return!1};t("createjs.EventDispatcher",C,{addEventListener:C.prototype.rh,on:C.prototype.Jb,removeEventListener:C.prototype.Ib,off:C.prototype.Ib,removeAllEventListeners:C.prototype.Pb,dispatchEvent:C.prototype.re,hasEventListener:C.prototype.ba,willTrigger:C.prototype.aj,contains:C.prototype.contains},{initialize:function(a){var b=C.prototype,c;for(c in b)a[c]||(a[c]=b[c])}});function ya(a,b){this.h=0<=a.indexOf("WebKit");var c;a:{c={Win:0,Mac:1,Linux:2,iPhone:4,iPad:4};for(var d in c)if(0<=b.indexOf(d)){c=c[d];c=2==c&&0<=a.indexOf("Android")?3:c;break a}c=5}this.g=c;var f;a:{c={Opera:0,MSIE:1,Trident:1,Edge:6};for(f in c)if(0<=a.indexOf(f)){f=c[f];break a}c={Chrome:2,Safari:3};d={Gecko:4,Firefox:4};c=this.h?c:d;for(f in c)if(0<=a.indexOf(f)){f=c[f];f=3==this.g&&3==f?5:f;break a}f=7}this.e=f;a:{f=this.g;if(4==f){if(f=a.match(/OS ([0-9]+)_([0-9]+)/)){f=1*f[1]+.1*f[2];break a}}else if(3==
f&&(f=a.match(/Android ([0-9]+)\.([0-9]+)/))){f=1*f[1]+.1*f[2];break a}f=0}this.l=f}var za=null;function Aa(){if(!za){var a=q.navigator;za=new ya(a?a.userAgent:"",a?a.platform:"")}return za}function Ba(a){return Aa().g==a};function Ca(a){a=a.match(Da);this.g=a[1];this.e=a[4]}var Da=/^(?:([^:/?#.]+:))?(?:\/\/([^/?#]*@)?([^/?#@]+)?)?([^?#]+)?(?:\?([^#]*))?(?:#(.*))?$/;function Ea(){this.e={}}var Fa=null;function Ga(a,b,c,d){var f;Fa||(Fa=new Ea);f=Fa;var g=f.e[a];g?g.complete||(g.addEventListener("load",c,!1),g.addEventListener("error",c,!1)):(g=document.createElement("img"),g.addEventListener("load",c,!1),g.addEventListener("error",c,!1),1684108385!=(b.charCodeAt(0)<<24)+(b.charCodeAt(1)<<16)+(b.charCodeAt(2)<<8)+b.charCodeAt(3)&&(g.crossOrigin="anonymous"),g.Eb=d,g.src=b,f.e[a]=g);return g}
function Ha(a,b){a.removeEventListener("load",b,!1);a.removeEventListener("error",b,!1)};var Ia=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,62,0,0,0,63,52,53,54,55,56,57,58,59,60,61,0,0,0,0,0,0,0,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,0,0,0,0,0,0,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,0,0,0,0,0];function F(a,b){this.e=A([a,b])}r(F,ja);F.prototype.Zc=function(){return this.e[0]};F.prototype.g=function(a){this.e[0]=a};F.prototype.nc=function(){return this.e[1]};F.prototype.h=function(a){this.e[1]=a};Object.defineProperties(F.prototype,{x:{get:F.prototype.Zc,set:F.prototype.g},y:{get:F.prototype.nc,set:F.prototype.h}});function G(a,b,c,d){this.x=a;this.y=b;this.width=c;this.height=d}r(G,ja);G.prototype.g=function(){return!this.width||!this.height};G.prototype.h=function(a,b){return this.x<=a&&a<=this.x+this.width&&this.y<=b&&b<=this.y+this.height};t("createjs.Rectangle",G,{});function Ja(a,b,c,d){this.color=a;this.g=b;this.h=c;this.e=d}r(Ja,ja);t("createjs.Shadow",Ja,{});function La(a,b,c){this.h=a;this.g=b;this.e=c}r(La,ja);function Ma(a,b,c){this.X=a;this.qa=b;this.pa=c}e=Ma.prototype;e.X=null;e.qa=0;e.pa=0;e.ie=-1;e.De=null;function Na(a){return"source-over source-atop source-in source-out destination-over destination-atop destination-in destination-out lighter copy xor darker multiply".split(" ")[a]}function Oa(a,b,c,d,f){this.m=a;this.l=new G(b.e[0],b.e[1],Pa(b),Qa(b));a=new Ra;a.e[0]=(c.e[0]|0)+1;a.e[1]=c.e[1]|0;a.e[2]=c.e[2]|0;a.e[3]=c.e[3]|0;this.g=a;this.h=d;this.e=1<d?f:null}
function Sa(a,b){0>a.ie&&(a.ie=ma[b]||0);var c=a.X;if(1==a.ie){var d=c.style.display;"none"!=d&&(c.style.display="none",c.offsetHeight,c.style.display=d)}else a.ie&&(c.width=c.width)}e.Hc=function(){};e.Cd=function(){};e.we=function(){};e.Xc=function(){};e.vg=function(){return 1};e.He=function(){};e.qd=function(){};e.Ud=function(){};e.Ic=function(){};e.nd=function(){};e.rb=function(){};e.le=function(){};e.Jc=function(){};function Ta(a,b){Ma.call(this,a,a.width,a.height);this.F=a.getContext("2d");a.setAttribute("dena-context","2d");b&&(this.F.beginPath(),this.F.rect(b.e[0],b.e[1],Pa(b),Qa(b)),this.F.clip())}r(Ta,Ma);e=Ta.prototype;e.F=null;e.Bc=1;e.Ac=0;e.mb=null;e.lb=null;function Ua(a){a.F.restore();a.Bc=-1;a.Ac=-1}function Va(a){a.F.setTransform(1,0,0,1,0,0);a.F.clearRect(0,0,a.qa+1,a.pa+1)}e.Hc=function(){this.lb&&(this.lb.Hc(),this.lb=null);this.F=null;this.X&&(this.X.width=0,this.X=null)};
e.Cd=function(a){this.F.setTransform(a[0],a[1],a[2],a[3],a[4],a[5]);var b=a[6];this.Bc!=b&&(this.Bc=b,this.F.globalAlpha=b);a=a[7];this.Ac!=a&&(this.Ac=a,this.F.globalCompositeOperation=Na(a))};e.Xc=function(a,b){this.F.drawImage(a,b[0],b[1],b[2],b[3])};e.He=function(a,b,c,d,f){this.F.drawImage(a,b,c,d,f)};e.Ic=function(a,b){this.F.drawImage(a,b[0],b[1],b[2],b[3],b[4],b[5],b[6],b[7])};
e.nd=function(a){var b;b=a.S;b=b.nb?b.nb.g:b.Xb;if(0>=b.e[2]||0>=b.e[3]||this.qa<=b.e[0]||this.pa<=b.e[1])Xa(a,this);else{if((b=a.S.nb)&&(b.e&&!b.e.V()?0:b.h)&&3!=b.h){if(b.e){if(2==b.h){var c;this.lb?Va(this.lb):(c=ia(),c.width=this.qa,c.height=this.pa,this.lb=new Ta(c,null));c=this.lb;Xa(a,c);a.va(c);a=b.e;Xa(a,c);a.va(c);this.F.setTransform(1,0,0,1,0,0);1!=this.Bc&&(this.Bc=1,this.F.globalAlpha=1);0!=this.Ac&&(this.Ac=0,this.F.globalCompositeOperation="source-over");this.F.drawImage(c.X,0,0,this.qa,
this.pa)}return}a:{b=b.g;if(this.mb){if(Ya(this.mb,b))break a;Ua(this)}this.mb=b;this.F.save();this.F.setTransform(1,0,0,1,0,0);this.F.beginPath();this.F.rect(b.e[0],b.e[1],Pa(b),Qa(b));this.F.clip()}}else this.mb&&(Ua(this),this.mb=null);Xa(a,this);a.va(this)}};e.le=function(){Va(this);Sa(this,"2d")};e.Jc=function(){this.mb&&(Ua(this),this.mb=null)};function Za(a,b,c){Ma.call(this,a,a.width,a.height);this.Va=new $a(b);this.Rd=2/this.qa;this.Sd=2/this.pa;this.md=c;a.setAttribute("dena-context",ab)}r(Za,Ma);var ab="",bb=0;e=Za.prototype;e.Va=null;e.Rd=1;e.Sd=1;e.md=null;e.Wa=null;e.Cb=null;e.j=!1;e.Bb=null;function $a(a){a.pixelStorei(37441,1);this.e=a;this.g=++bb}$a.prototype.e=null;$a.prototype.g=0;$a.prototype.H=null;function cb(a,b,c){a=a.e;b=a.createShader(b);a.shaderSource(b,c);a.compileShader(b);return b}
function db(a,b,c){a=a.e;a.bindBuffer(34962,b);a.bufferData(34962,c,35044)}function eb(a,b){a.H!==b&&(a.e.bindTexture(3553,b),a.H=b)}function fb(a,b,c){var d=b.e[0],f=b.e[3];a.e.scissor(d,c-f,b.e[2]-d,f-b.e[1])}function gb(a,b,c,d){this.j=!0;this.g=a.e.getUniformLocation(b,c);this.e=d}gb.prototype.j=!1;gb.prototype.g=null;gb.prototype.e=0;function hb(a,b,c,d,f){this.j=!0;this.ig=a.e.getUniformLocation(b,c);this.C=d;this.D=f}e=hb.prototype;e.j=!1;e.ig=null;e.C=0;e.D=0;
e.set=function(a,b){if(this.C!=a||this.D!=b)this.j=!0,this.C=a,this.D=b};function ib(a,b,c,d,f){d=this.e=new Float32Array([0,0,d,0,0,f,d,f]);f=a.e.createBuffer();db(a,f,d);this.g=f;a=a.e;b=a.getAttribLocation(b,c);a.enableVertexAttribArray(b);a.vertexAttribPointer(b,2,5126,!1,0,0)}ib.prototype.e=null;ib.prototype.g=null;ib.prototype.set=function(a,b,c,d){c=a+c;d=b+d;this.e[0]=a;this.e[1]=b;this.e[2]=c;this.e[3]=b;this.e[4]=a;this.e[5]=d;this.e[6]=c;this.e[7]=d};
function jb(a,b,c){this.g=a.e.getUniformLocation(b,c);this.e=new Float32Array([1,0,0,0,1,0,0,0,1])}jb.prototype.g=null;jb.prototype.e=null;jb.prototype.set=function(a,b,c,d,f,g){this.e[0]=a;this.e[1]=b;this.e[3]=c;this.e[4]=d;this.e[6]=f;this.e[7]=g};function kb(a,b,c){this.j=!0;this.g=a.e.getUniformLocation(b,c);this.e=new Float32Array([1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1])}kb.prototype.j=!1;kb.prototype.g=null;kb.prototype.e=null;
kb.prototype.set=function(a){this.j=!0;this.e[0]=a[0];this.e[1]=a[5];this.e[2]=a[10];this.e[4]=a[1];this.e[5]=a[6];this.e[6]=a[11];this.e[8]=a[2];this.e[9]=a[7];this.e[10]=a[12]};function lb(a,b,c,d,f,g){this.j=!0;this.hg=a.e.getUniformLocation(b,c);this.Md=d;this.Ld=f;this.Kd=g}e=lb.prototype;e.j=!1;e.hg=null;e.Md=0;e.Ld=0;e.Kd=0;e.set=function(a,b,c){if(this.Md!=a||this.Ld!=b||this.Kd!=c)this.j=!0,this.Md=a,this.Ld=b,this.Kd=c};
function mb(a){this.j=!0;this.e=0;a=a.e;a.enable(3042);a.blendEquation(32774)}mb.prototype.j=!1;mb.prototype.e=0;function nb(a,b,c,d){var f=a.e,g=f.createTexture();f.bindTexture(3553,g);f.texParameteri(3553,10242,33071);f.texParameteri(3553,10243,33071);f.texParameteri(3553,10241,9729);f.texParameteri(3553,10240,9729);f.texImage2D(3553,0,6408,b,c,0,6408,d,null);b=this.H=a.H=g;a=a.e;c=a.createFramebuffer();a.bindFramebuffer(36160,c);a.framebufferTexture2D(36160,36064,3553,b,0);this.e=c}
nb.prototype.H=null;nb.prototype.e=null;function ob(a){this.g=cb(a,35633,"attribute vec2 p;attribute vec2 t;uniform vec2 s;uniform mat3 x;varying vec2 u;void main(){vec3 v=x*vec3(p[0],p[1],1);gl_Position=vec4(v[0]*s[0]-1.0,v[1]*s[1]+1.0,0,1);u=t;}");this.e=cb(a,35632,"precision mediump float;varying vec2 u;uniform vec4 a;uniform mat4 m;uniform vec4 c;uniform sampler2D i;void main(){vec4 v=texture2D(i,u);gl_FragColor=a*(m*v+c*v[3]);}")}
function pb(a,b,c){this.zb=a;this.e=new ob(a);var d=this.e.e,f=a.e,g=f.createProgram();f.attachShader(g,this.e.g);f.attachShader(g,d);f.linkProgram(g);f.useProgram(g);this.Ua=g;this.Ve=new hb(a,this.Ua,"s",b,-c);this.Qd=new jb(a,this.Ua,"x");this.Ab=new ib(a,this.Ua,"p",0,0);this.H=new ib(a,this.Ua,"t",1,1);this.Nd=new gb(a,this.Ua,"a",1);this.Pd=new kb(a,this.Ua,"m");this.Od=new lb(a,this.Ua,"c",0,0,0);this.rd=new mb(a)}e=pb.prototype;e.zb=null;e.Ua=null;e.Ve=null;e.Qd=null;e.Ab=null;e.H=null;
e.Nd=null;e.Pd=null;e.Od=null;e.rd=null;function qb(a,b){var c;c=a.zb;var d=b.H,f=b.g;if(d&&f==c.g)c=!1;else{var d=c.e,f=d.createTexture(),g=[5121,32819,32820,33635][b.Eb||0];d.bindTexture(3553,f);d.texParameteri(3553,10242,33071);d.texParameteri(3553,10243,33071);d.texParameteri(3553,10241,9729);d.texParameteri(3553,10240,9729);d.texImage2D(3553,0,6408,6408,g,b);c.H=f;b.H=f;b.g=c.g;c=!0}c||(c=a.zb,eb(c,b.H),b.j&&(b.j=!1,c.e.texImage2D(3553,0,6408,6408,[5121,32819,32820,33635][b.Eb||0],b)))}
function rb(a){var b=a.zb,c=a.Qd;b.e.uniformMatrix3fv(c.g,!1,c.e);c=a.Ab;db(b,c.g,c.e);c=a.H;db(b,c.g,c.e);c=a.Nd;c.j&&(c.j=!1,b.e.uniform4f(c.g,c.e,c.e,c.e,c.e));c=a.Pd;c.j&&(c.j=!1,b.e.uniformMatrix4fv(c.g,!1,c.e));c=a.Od;c.j&&(c.j=!1,b.e.uniform4f(c.hg,c.Md,c.Ld,c.Kd,0));a=a.rd;a.j&&(a.j=!1,a=a.e,c=[1,771,772,1,772,0,773,0,773,1,1,770,0,770,0,771,1,1,1,0,773,771,774,1,0,768],a<<=1,b.e.blendFunc(c[a],c[a+1]));b.e.drawArrays(5,0,4)}function sb(a){a.Cb||(a.Cb=new pb(a.Va,a.Rd,a.Sd));return a.Cb}
e=Za.prototype;e.Hc=function(){var a=this.Va;if(a){if(this.Bb){var b=this.Bb;a.e.deleteFramebuffer(b.e);a.e.deleteTexture(b.H);this.Bb=null}if(b=this.Cb)a.e.deleteBuffer(b.Ab.g),a.e.deleteBuffer(b.H.g),a.e.deleteProgram(b.Ua),b=b.e,a.e.deleteShader(b.g),a.e.deleteShader(b.e),this.Cb=null}};e.Cd=function(a){sb(this).Qd.set(a[0],a[1],a[2],a[3],a[4],a[5]);var b=sb(this).Nd,c=a[6];b.e!=c&&(b.j=!0,b.e=c);b=sb(this).rd;a=a[7];b.e!=a&&(b.j=!0,b.e=a)};
e.we=function(a){var b=sb(this);if(a){var c=1/255;b.Pd.set(a);b.Od.set(a[4]*c,a[9]*c,a[14]*c)}else a=b.Pd,a.e[0]=1,a.e[1]=0,a.e[2]=0,a.e[4]=0,a.e[5]=1,a.e[6]=0,a.e[8]=0,a.e[9]=0,a.e[10]=1,b.Od.set(0,0,0)};e.Xc=function(a,b){var c=sb(this);c.Ab.set(b[0],b[1],b[2],b[3]);c.H.set(0,0,1,1);qb(c,a);rb(c)};e.vg=function(){return 1==Aa().e?0:1};e.He=function(a,b,c,d,f){var g=sb(this);g.Ab.set(b,c,d,f);g.H.set(0,0,1,1);qb(g,a);rb(g)};
e.Ic=function(a,b){a.e||(a.e=new Float32Array([1/a.width,1/a.height]));if(!b[11]){var c=a.e[0],d=a.e[1];b[8]=b[0]*c;b[9]=b[1]*d;b[10]=b[2]*c;b[11]=b[3]*d}var c=sb(this),d=b[8],f=b[9],g=b[10],h=b[11];c.Ab.set(b[4],b[5],b[6],b[7]);c.H.set(d,f,g,h);qb(c,a);rb(c)};
e.nd=function(a){var b=this.Va;if(b.g){a:{var c=this.qa,d=this.pa,f=a.S.nb;if(f&&(f.e&&!f.e.V()?0:f.h)){if(f.e){var g;this.Bb?b.e.bindFramebuffer(36160,this.Bb.e):this.Bb=new nb(b,this.qa,this.pa,32819);b.e.clear(16384);g=this.Bb;var h=this.Wa||this.md;h||b.e.enable(3089);fb(b,f.g,d);Xa(a,this);a.va(this);a=f.e;Xa(a,this);a.va(this);h?fb(b,h,d):b.e.disable(3089);b.e.bindFramebuffer(36160,null);b=this.Cb;b.Ab.set(0,0,c,d);b.H.set(0,0,1,1);b.Qd.set(1,0,0,-1,0,d);d=b.Nd;1!=d.e&&(d.j=!0,d.e=1);d=b.rd;
0!=d.e&&(d.j=!0,d.e=0);eb(b.zb,g.H);rb(b);break a}g=f.g;this.Wa&&Ya(this.Wa,g)||(this.Wa||this.md||b.e.enable(3089),this.Wa=g,fb(b,g,d))}else this.Wa&&(this.md?fb(b,this.md,d):b.e.disable(3089),this.Wa=null);Xa(a,this);a.va(this)}this.j=!0}};e.rb=function(a){var b=sb(this),c=a.H;a.H=null;a=b.zb;c&&a&&a.e.deleteTexture(c)};
e.le=function(){var a=this.X,b=a.width,a=a.height;if(b!=this.qa||a!=this.pa)this.qa=b,this.pa=a,this.Rd=2/b,this.Sd=2/a,this.Va.e.viewport(0,0,b,a);a=sb(this);a.Ve.set(this.Rd,-this.Sd);b=a.Ve;a=a.zb;b.j&&(b.j=!1,a.e.uniform2f(b.ig,b.C,b.D))};e.Jc=function(){if(this.Va.g){sb(this);var a=this.Va;this.j||(a.e.clear(16384),Sa(this,"webgl"));this.Wa&&(a.e.disable(3089),this.Wa=null);this.j=!1}};
e.handleEvent=function(a){"webglcontextlost"==a.type?(this.Cb=null,this.Va.g=0,a.preventDefault()):(a=++bb,this.Va.g=a)};function tb(a){this.e=a}r(tb,ja);tb.prototype.Za=function(){return null};tb.prototype.m=function(){return!1};t("createjs.Filter",tb,{getBounds:tb.prototype.Za,applyFilter:tb.prototype.m});function ub(a){this.e=0;this.g=a}r(ub,tb);ub.prototype.g=null;t("createjs.AlphaMapFilter",ub,{});function vb(a,b,c,d,f,g,h){this.e=3;this.l=new La(null!=a?a:1,null!=b?b:1,null!=c?c:1);this.g=new La(f||0,g||0,h||0)}r(vb,tb);vb.prototype.l=null;vb.prototype.g=null;t("createjs.ColorFilter",vb,{});function H(a,b,c,d){this.Bf(a,b,c,d)}r(H,ja);e=H.prototype;e.n=null;e.Bf=function(a,b,c,d){return this.Af().hf(a,b,c,d)};e.Af=function(){this.n=new Float32Array([1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,1]);return this};e.hf=function(a,b,c,d){this.kf(d);this.jf(b);this.gf(a);this.mf(c);return this};e.gf=function(a){if(a&&a===a)for(var b=0;20>b;b+=5)this.n[b+4]+=this.n[b+0]*a+this.n[b+1]*a+this.n[b+2]*a;return this};
e.jf=function(a){if(a&&a===a){var b=1,c=0;if(0>a)b=1+.01*a,c=-.635*a;else{var b=[0,.01,.02,.04,.05,.06,.07,.08,.1,.11,.12,.14,.15,.16,.17,.18,.2,.21,.22,.24,.25,.27,.28,.3,.32,.34,.36,.38,.4,.42,.44,.46,.48,.5,.53,.56,.59,.62,.65,.68,.71,.74,.77,.8,.83,.86,.89,.92,.95,.98,1,1.06,1.12,1.18,1.24,1.3,1.36,1.42,1.48,1.54,1.6,1.66,1.72,1.78,1.84,1.9,1.96,2,2.12,2.25,2.37,2.5,2.62,2.75,2.87,3,3.2,3.4,3.6,3.8,4,4.3,4.7,4.9,5,5.5,6,6.5,6.8,7,7.3,7.5,7.8,8,8.4,8.7,9,9.4,9.6,9.8,10],c=a|0,d=a-c;d?a=b[c]*(1-
d)+b[c+1]*d:a=b[c];b=1+a;c=-63.5*a}for(a=0;20>a;a+=5){var d=this.n[a+0],f=this.n[a+1],g=this.n[a+2];this.n[a+0]*=b;this.n[a+1]*=b;this.n[a+2]*=b;this.n[a+4]+=d*c+f*c+g+c}}return this};e.mf=function(a){if(a&&a===a){var b=a*(0<a?-.03:-.01),c=1+c;a=.3086*b;for(var d=a+c,f=.6094*b,g=a+c,b=.082*b,c=a+c,h=0;20>h;++h){var k=this.n[h+0],l=this.n[h+1],m=this.n[h+2];this.n[h+0]=k*d+l*a+m*a;this.n[h+1]=k*f+l*g+m*f;this.n[h+2]=k*b+l*b+m*c}}return this};
e.kf=function(a){if(a&&a===a){var b=Math.cos(.017453292519943295*a),c=Math.sin(.017453292519943295*a);a=.213+.787*b+-.213*c;for(var d=.213+-.213*b+.143*c,f=.213+-.213*b+-.787*c,g=.715+-.715*b+-.715*c,h=.715+b*(1-.715)+.14*c,k=.715+-.715*b+.715*c,l=.072+-.072*b+.928*c,m=.072+-.072*b+-.283*c,b=.072+.928*b+.072*c,c=0;20>c;c+=5){var n=this.n[c+0],p=this.n[c+1],s=this.n[c+2];this.n[c+0]=n*a+p*d+s*f;this.n[c+1]=n*g+p*h+s*k;this.n[c+2]=n*l+p*m+s*b}}return this};
e.bh=function(a){for(var b=0;20>b;b+=5)for(var c=this.n[b+0],d=this.n[b+1],f=this.n[b+2],g=this.n[b+3],h=this.n[b+4],k=0;5>k;++k)this.n[b+k]=c*a[0+k]+d*a[5+k]+f*a[10+k]+g*a[15+k]+h*a[20+k];return this};e.ah=function(a){for(var b=0;25>b;++b)this.n[b]=a[b];return this};e.Yg=function(){return this.n};
t("createjs.ColorMatrix",H,{setColor:H.prototype.Bf,reset:H.prototype.Af,adjustColor:H.prototype.hf,adjustBrightness:H.prototype.gf,adjustContrast:H.prototype.jf,adjustSaturation:H.prototype.mf,adjustHue:H.prototype.kf,concat:H.prototype.bh,copy:H.prototype.ah,toArray:H.prototype.Yg});function wb(a){this.e=4;this.h=a}r(wb,tb);wb.prototype.h=null;t("createjs.ColorMatrixFilter",wb,{});function xb(){}function yb(a,b){var c=ia();c.width=a;c.height=b;this.g=c;this.e=c.getContext("2d")}xb.prototype.e=null;xb.prototype.g=null;function zb(a){return a.e?a.e.g:null};function Ab(a,b,c,d,f,g,h,k,l,m){this.e=a;this.stageX=d;this.stageY=f;this.nativeEvent=g;this.pointerID=h;this.primary=k;this.rawX=l;this.rawY=m}r(Ab,B);function Ra(){this.e=A([1E4,1E4,-1E4,-1E4])}r(Ra,ja);function Pa(a){return a.e[2]-a.e[0]}function Qa(a){return a.e[3]-a.e[1]}function Ya(a,b){return a.e[0]==b.e[0]&&a.e[2]==b.e[2]&&a.e[1]==b.e[1]&&a.e[3]==b.e[3]}function J(a,b,c){a.e[0]=u(b,a.e[0]);a.e[1]=u(c,a.e[1]);a.e[2]=z(b,a.e[2]);a.e[3]=z(c,a.e[3])}Ra.prototype.g=function(){return this.e[2]<=this.e[0]};Ra.prototype.h=function(a,b){return this.e[0]<=a&&a<=this.e[2]&&this.e[1]<=b&&b<=this.e[3]};function Bb(){this.e=A([1,0,0,1,0,0,1,0])}Bb.prototype.j=0;
Bb.prototype.set=function(a){var b=a[2],c=0,d=0,f=a[3];this.j=1!=b||1!=f?1:0;var g=a[8];if(g){var h=Math.cos(.017453292519943295*g),d=Math.sin(.017453292519943295*g),c=d*b,d=-d*f,b=h*b,f=h*f;this.j|=2}var k=a[4],g=a[5];if(k||g){var h=Math.cos(.017453292519943295*g),g=Math.sin(.017453292519943295*g),l=-Math.sin(.017453292519943295*k),k=Math.cos(.017453292519943295*k),m=b,n=d,b=h*m+l*c,c=g*m+k*c,d=h*n+l*f,f=g*n+k*f;this.j|=2}h=this.e;h[0]=b;h[1]=c;h[2]=d;h[3]=f;h[4]=a[0];h[5]=a[1];g=a[6];a=a[7];if(g||
a)h[4]-=g*b+a*d,h[5]-=g*c+a*f;h[15]=0};function Cb(a){var b=a.e;a=b[0];var c=b[1],d=b[2],f=b[3],g=a*f-c*d;if(!g)return null;var g=1/g,h=b[4],b=b[5],k=new Bb;k.e[0]=f*g;k.e[1]=-c*g;k.e[2]=-d*g;k.e[3]=a*g;k.e[4]=(d*b-f*h)*g;k.e[5]=-(a*b-c*h)*g;return k}function Db(a,b){var c=b.e[0],d=b.e[1],f=a.e;b.e[0]=f[0]*c+f[2]*d+f[4];b.e[1]=f[1]*c+f[3]*d+f[5];return b};function K(){this.A=new Ra;this.Aa=[];this.N=[];this.Yb=A([0,0,0,0])}r(K,ja);e=K.prototype;e.A=null;e.Aa=null;e.N=null;e.Ba=null;e.Oe="";e.gd=!1;e.j=!1;e.ob=null;e.Ye=null;e.Oa=null;e.Re=0;e.Yb=null;function Eb(a){this.g=ia();this.e=this.g.getContext("2d");a&2&&(this.g.Eb=1)}e=Eb.prototype;e.Pf=0;e.Nf=0;e.Ec=1;e.Fc=1;e.Hg=1;e.Of=1;e.Cg=0;e.Dg=0;e.Eg=10;e.Vd="";e.ee="";e.vd=null;function Fb(a){a.g&&(a.vd&&(a.vd.rb(a.g),a.vd=null),a.g.width=0);a.e=null;a.g=null}
function Gb(a,b,c,d,f,g){this.e=a;this.g=b;this.h=c;this.m=d;this.l=f;this.J=g}function Hb(a,b){for(var c=a.e,d=a.g,f=b.e.createLinearGradient(a.h,a.m,a.l,a.J),g=0;g<c.length;++g)f.addColorStop(d[g],c[g]);return f}function Ib(a){return a.e.join()+","+a.g.join()+","+a.h+","+a.m+","+a.l+","+a.J}function Jb(a,b,c,d,f,g,h,k){this.e=a;this.g=b;this.h=c;this.m=d;this.$a=f;this.l=g;this.J=h;this.qc=k}
function Kb(a,b){for(var c=a.e,d=a.g,f=b.e.createRadialGradient(a.h,a.m,a.$a,a.l,a.J,a.qc),g=0;g<c.length;++g)f.addColorStop(d[g],c[g]);return f}function Lb(a){return a.e.join()+","+a.g.join()+","+a.h+","+a.m+","+a.$a+","+a.l+","+a.J+","+a.qc}function Mb(){return""}function Nb(a,b){this.C=a;this.D=b}Nb.prototype.e=function(a){a.e.moveTo(this.C,this.D)};Nb.prototype.g=function(){return"M,"+this.C+","+this.D};function Ob(a,b){this.C=a;this.D=b}Ob.prototype.e=function(a){a.e.lineTo(this.C,this.D)};
Ob.prototype.g=Mb;function Pb(a,b,c,d,f){this.l=a;this.J=b;this.m=c;this.$a=d;this.h=f}Pb.prototype.e=function(a){a.e.arcTo(this.l,this.J,this.m,this.$a,this.h)};Pb.prototype.g=Mb;function Qb(a,b,c,d,f,g){this.C=a;this.D=b;this.l=c;this.J=d;this.m=f;this.h=g}Qb.prototype.e=function(a){a.e.arc(this.C,this.D,this.l,this.J,this.m,this.h)};Qb.prototype.g=Mb;function Rb(a,b,c,d){this.h=a;this.l=b;this.C=c;this.D=d}Rb.prototype.e=function(a){a.e.quadraticCurveTo(this.h,this.l,this.C,this.D)};
Rb.prototype.g=function(){return"Q,"+this.h+","+this.l+","+this.C+","+this.D};function Sb(a,b,c,d,f,g){this.h=a;this.l=b;this.m=c;this.J=d;this.C=f;this.D=g}Sb.prototype.e=function(a){a.e.bezierCurveTo(this.h,this.l,this.m,this.J,this.C,this.D)};Sb.prototype.g=Mb;function Tb(a,b,c,d){this.C=a;this.D=b;this.l=c;this.h=d}Tb.prototype.e=function(a){a.e.rect(this.C,this.D,this.l,this.h)};Tb.prototype.g=Mb;function Ub(){}var Vb=null;function Wb(){Vb||(Vb=new Ub);return Vb}Ub.prototype.e=function(a){a.e.beginPath()};
Ub.prototype.g=Mb;function Xb(){}var Yb=null;function Zb(){Yb||(Yb=new Xb);return Yb}Xb.prototype.e=function(a){a.e.closePath()};Xb.prototype.g=function(){return"C"};function $b(a){this.h=a}$b.prototype.e=function(a){var b=this.h;a.Vd!=b&&(a.Vd=b,a.e.fillStyle=b)};$b.prototype.g=function(){return"F"+this.h};function ac(a,b,c,d,f,g){this.h=new Gb(a,b,c,d,f,g)}ac.prototype.e=function(a){var b=Hb(this.h,a);a.e.fillStyle=b;a.Vd=""};ac.prototype.g=function(){return"LF"+Ib(this.h)};
function bc(a,b,c,d,f,g,h,k){this.h=new Jb(a,b,c,d,f,g,h,k)}bc.prototype.e=function(a){var b=Kb(this.h,a);a.e.fillStyle=b;a.Vd=""};bc.prototype.g=function(){return"RF"+Lb(this.h)};function cc(a,b,c,d){this.J=a;this.h=b;this.l=c;this.m=d}cc.prototype.e=function(a){var b=this.J,c=this.h,d=this.l,f=this.m;a.Of!=b&&(a.Of=b,a.e.lineWidth=b);a.Cg!=c&&(a.Cg=c,a.e.lineCap=["butt","round","square"][c]);a.Dg!=d&&(a.Dg=d,a.e.lineJoin=["miter","round","bevel"][d]);a.Eg!=f&&(a.Eg=f,a.e.miterLimit=f)};
cc.prototype.g=function(){return"L,"+this.J+","+this.h+","+this.l+","+this.m};function dc(a){this.h=a}dc.prototype.e=function(a){var b=this.h;a.ee!=b&&(a.ee=b,a.e.strokeStyle=b)};dc.prototype.g=function(){return"S"+this.h};function ec(a,b,c,d,f,g){this.h=new Gb(a,b,c,d,f,g)}ec.prototype.e=function(a){var b=Hb(this.h,a);a.e.strokeStyle=b;a.ee=""};ec.prototype.g=function(){return"LS"+Ib(this.h)};function fc(a,b,c,d,f,g,h,k){this.h=new Jb(a,b,c,d,f,g,h,k)}
fc.prototype.e=function(a){var b=Kb(this.h,a);a.e.strokeStyle=b;a.ee=""};fc.prototype.g=function(){return"RS"+Lb(this.h)};function gc(a,b){this.h=a;this.l=b}var hc=[null,null,null,null];function ic(a,b){var c=(a?2:0)|(b?1:0);hc[c]||(hc[c]=new gc(a,b));return hc[c]}gc.prototype.e=function(a){var b=this.l;this.h&&a.e.fill();b&&a.e.stroke()};gc.prototype.g=function(){return"P"+((this.h?2:0)|(this.l?1:0))};
function jc(a){this.l=++kc;for(var b=this.h=new Ra,c=[],d=0,f=0,g=0,h=a.length;g<h;){var k=Ia[a.charCodeAt(g++)],l=k>>3,k=(k>>2&1)+2;if(4==l)c.push(Zb());else if(0==l&&(f=d=0),d+=lc(a,g,k),g+=k,f+=lc(a,g,k),g+=k,J(b,d,f),0==l)c.push(new Nb(d,f));else if(1==l)c.push(new Ob(d,f));else{var m=d,n=f,d=d+lc(a,g,k),g=g+k,f=f+lc(a,g,k),g=g+k;J(b,d,f);if(2==l)c.push(new Rb(m,n,d,f));else{var l=d,p=f,d=d+lc(a,g,k),g=g+k,f=f+lc(a,g,k),g=g+k;J(b,d,f);c.push(new Sb(m,n,l,p,d,f))}}}this.m=c}var kc=0,mc={};
function nc(a,b){var c=mc[a];c||(c=new jc(a),mc[a]=c);J(b,c.h.e[0],c.h.e[1]);J(b,c.h.e[2],c.h.e[3]);return c}function lc(a,b,c){var d=Ia[a.charCodeAt(b)],f=d>>5?-.1:.1,d=(d&31)<<6|Ia[a.charCodeAt(b+1)];3==c&&(d=d<<6|Ia[a.charCodeAt(b+2)]);return d*f}jc.prototype.e=function(a){for(var b=this.m,c=b.length,d=0;d<c;++d)b[d].e(a)};jc.prototype.g=function(){return"D"+this.l};var oc={};
function pc(a,b){if(!b)return 0;if("number"==typeof b)return b;for(var c=a.length,d=0;d<c;++d)if(a[d]==b)return d;return 0}function qc(a){a.Aa.push(Wb());a.Oa&&a.Aa.push(a.Oa);a.ob&&(a.Aa.push(a.ob),a.Ye&&a.Aa.push(a.Ye));0!=a.N.length&&a.Aa.push.apply(a.Aa,a.N);a.Aa.push(ic(!!a.Oa,!!a.ob));a.gd=!0}function rc(a){a.N.length&&(a.j&&(qc(a),a.j=!1),a.N=[])}
function sc(a,b){a.j&&(b&2&&!a.Oa&&(a.Oa=new $b("#000")),qc(a),a.j=!1,a.N=[]);if(a.gd)a:{a.gd=!1;var c=a.A,d=a.Re;c.e[0]-=d;c.e[1]-=d;c.e[2]+=d;c.e[3]+=d;c.e[2]=c.e[0]+(c.e[2]-c.e[0]|0);c.e[3]=c.e[1]+(c.e[3]-c.e[1]|0);var f=Pa(c),g=Qa(c);a.Yb[0]=c.e[0];a.Yb[1]=c.e[1];a.Yb[2]=f;a.Yb[3]=g;if(!(1>f||1>g)){for(var d=a.Aa,h=d.length,k="",l=1;l<h;++l){var m=d[l].g();if(!m){k="";break}k+=m}if(k&&(m=oc[k])){++m.Hg;a.Ba=m;a.Oe=k;break a}m=k;tc(a);a.Ba=new Eb(b);a.Oe=m;var l=m=a.Ba,n=c.e[0],c=c.e[1];l.Ec=1;
128<f&&(l.Ec=128/f,n*=l.Ec,f=128);l.Fc=1;128<g&&(l.Fc=128/g,c*=l.Fc,g=128);l.Pf!=f&&(l.Pf=f,l.g.width=f);l.Nf!=g&&(l.Nf=g,l.g.height=g);l.e.setTransform(l.Ec,0,0,l.Fc,-n,-c);l.e.clearRect(0,0,f,g);for(l=0;l<h;++l)d[l].e(m);k&&(oc[k]=m)}}}function tc(a){if(a.Ba){var b=a.Ba,c=--b.Hg;0>=c&&Fb(b);0>=c&&(b=a.Oe)&&(oc[b]=null);a.Ba=null;a.gd=!0}}e=K.prototype;e.Vf=function(a,b){J(this.A,a,b);this.N.push(new Nb(a,b));return this};e.Uf=function(a,b){this.j=!0;J(this.A,a,b);this.N.push(new Ob(a,b));return this};
e.Qf=function(a,b,c,d,f){this.j=!0;J(this.A,a,b);J(this.A,c,d);this.N.push(new Pb(a,b,c,d,f));return this};e.se=function(a,b,c,d,f,g){this.j=!0;J(this.A,a-c,b-c);J(this.A,a+c,b+c);this.N.push(new Qb(a,b,c,d,f,g));return this};e.te=function(a,b,c,d){this.j=!0;J(this.A,a,b);J(this.A,c,d);this.N.push(new Rb(a,b,c,d));return this};e.Rf=function(a,b,c,d,f,g){this.j=!0;J(this.A,a,b);J(this.A,c,d);J(this.A,f,g);this.N.push(new Sb(a,b,c,d,f,g));return this};
e.wd=function(a,b,c,d){this.j=!0;J(this.A,a,b);J(this.A,a+c,b+d);this.N.push(new Tb(a,b,c,d));return this};e.Tf=function(){0<this.N.length&&(this.j=!0,this.N.push(Zb()));return this};e.Sf=function(){tc(this);var a=this.A;a.e[0]=1E4;a.e[1]=1E4;a.e[2]=-1E4;a.e[3]=-1E4;this.j=!1;this.Aa=[];this.ob=this.Oa=null;this.N=[];return this};e.qf=function(a){rc(this);a&&(this.Oa=new $b(a));return this};e.sf=function(a,b,c,d,f,g){rc(this);this.Oa=new ac(a,b,c,d,f,g);return this};
e.uf=function(a,b,c,d,f,g,h,k){rc(this);this.Oa=new bc(a,b,c,d,f,g,h,k);return this};e.of=function(){return this};e.sg=function(){rc(this);return this};e.Sg=function(a,b,c,d){rc(this);a=null==a?1:a;b=pc(["butt","round","square"],b);c=pc(["miter","round","bevel"],c);this.Ye=new cc(a,b,c,null==d?10:d);this.Re=z(a,this.Re);return this};e.wf=function(a){rc(this);a&&(this.ob=new dc(a));return this};e.tf=function(a,b,c,d,f,g){rc(this);this.ob=new ec(a,b,c,d,f,g);return this};
e.vf=function(a,b,c,d,f,g,h,k){rc(this);this.ob=new fc(a,b,c,d,f,g,h,k);return this};e.pf=function(){return this};e.tg=function(){rc(this);return this};e.og=function(){return this};e.pg=function(){return this};e.lg=function(a,b,c){this.se(a,b,c,0,7,!1);return this};
e.mg=function(a,b,c,d){this.j=!0;J(this.A,a,b);J(this.A,a+c,b+d);var f=.2761424*c,g=.2761424*d,h=a+c,k=b+d;c=a+.5*c;d=b+.5*d;this.N.push(new Nb(a,d),new Sb(a,d-g,c-f,b,c,b),new Sb(c+f,b,h,d-g,h,d),new Sb(h,d+g,c+f,k,c,k),new Sb(c-f,k,a,d+g,a,d));return this};e.Hi=function(){return this};e.ng=function(){return this};e.jg=function(a){this.j=!0;this.N.push(nc(a,this.A));return this};
t("createjs.Graphics",K,{moveTo:K.prototype.Vf,lineTo:K.prototype.Uf,arcTo:K.prototype.Qf,arc:K.prototype.se,quadraticCurveTo:K.prototype.te,bezierCurveTo:K.prototype.Rf,rect:K.prototype.wd,closePath:K.prototype.Tf,clear:K.prototype.Sf,beginFill:K.prototype.qf,beginLinearGradientFill:K.prototype.sf,beginRadialGradientFill:K.prototype.uf,beginBitmapFill:K.prototype.of,endFill:K.prototype.sg,setStrokeStyle:K.prototype.Sg,beginStroke:K.prototype.wf,beginLinearGradientStroke:K.prototype.tf,beginRadialGradientStroke:K.prototype.vf,
beginBitmapStroke:K.prototype.pf,endStroke:K.prototype.tg,curveTo:K.prototype.te,drawRect:K.prototype.wd,drawRoundRect:K.prototype.og,drawRoundRectComplex:K.prototype.pg,drawCircle:K.prototype.lg,drawEllipse:K.prototype.mg,inject:K.prototype.Hi,drawPolyStar:K.prototype.ng,decodePath:K.prototype.jg,mt:K.prototype.Vf,lt:K.prototype.Uf,at:K.prototype.Qf,a:K.prototype.se,qt:K.prototype.te,bt:K.prototype.Rf,r:K.prototype.wd,cp:K.prototype.Tf,c:K.prototype.Sf,f:K.prototype.qf,lf:K.prototype.sf,rf:K.prototype.uf,
bf:K.prototype.of,ef:K.prototype.sg,ss:K.prototype.Sg,s:K.prototype.wf,ls:K.prototype.tf,rs:K.prototype.vf,bs:K.prototype.pf,es:K.prototype.tg,dr:K.prototype.wd,rr:K.prototype.og,rc:K.prototype.pg,dc:K.prototype.lg,de:K.prototype.mg,dp:K.prototype.ng,p:K.prototype.jg},{getRGB:function(a,b,c,d){var f=arguments.length;if(2>=f){var g=a>>16&255,h=a>>8&255,k=a&255;if(1==f)return"rgb("+g+","+h+","+k+")";f=b}else{g=a;h=b;k=c;if(3==f)return"rgb("+g+","+h+","+k+")";f=d}return"rgba("+g+","+h+","+k+","+f+")"},
getHSL:function(a,b,c,d){a%=360;return null==d?"hsl("+a+","+b+"%,"+c+"%)":"hsla("+a+","+b+"%,"+c+"%,"+d+")"}});function uc(){this.e=A([0,0,0])}uc.prototype.h=null;uc.prototype.g=null;function vc(){this.ta=[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null];this.e=A([0,0,1,1,0,0,0,0,0,1,0,0,0,1,1])}function wc(a,b,c,d,f){this.l=a;this.m=b;this.e=c;this.g=d;this.h=f}wc.prototype.R=function(a,b,c){return c+57.29577951308232*Math.atan2(b*this.m+a*this.g,b*this.l+a*this.e)+this.h*a};wc.prototype.Le=function(a){return a+57.29577951308232*Math.atan2(this.g,this.e)+this.h};
function xc(a,b,c,d){this.C=a;this.D=b;this.fe=c;this.L=0;this.ua=d;this.xa=this.Wg=0}function yc(a,b,c){this.h=a[b];this.l=a[b+1];this.J=a[b+2];this.$a=a[b+3];this.e=a[b+4];this.g=a[b+5];this.Fg=[];this.qc=this.uc=0;this.L=c;this.ua=-1;this.m=null}
yc.prototype.R=function(a,b,c,d){a-=this.L;for(var f=this.qc;f<this.uc;++f){var g=this.Fg[f],h=a-g.L;if(h<g.ua){a=g.Wg+h*g.xa;var g=1-a,h=g*g,k=2*g*a,l=a*a;b[c]=h*this.h+k*this.J+l*this.e;b[c+1]=h*this.l+k*this.$a+l*this.g;this.m?(b[c+2]=1,b[c+3]=this.m.R(a,g,d)):(b[c+2]=0,b[c+3]=0);this.qc=f;return!0}}this.qc=0;return!1};yc.prototype.Le=function(a,b,c){a[b]=this.e;a[b+1]=this.g;this.m?(a[b+2]=1,a[b+3]=this.m.Le(c)):(a[b+2]=0,a[b+3]=0)};e=vc.prototype;e.ta=null;e.Ea=0;e.ka=0;e.L=0;e.fc=0;e.ze=0;
e.xa=0;e.ec=null;e.dd=!0;e.hc="";e.gc=null;e.sa=null;e.Zc=function(){return this.e[0]};e.nc=function(){return this.e[1]};function zc(a,b){for(var c,d=0;14>=d;++d)c=a.ta[d],b.e[d]=c?c.e[1]:a.e[d];c=a.ta[15];b.hc=c?c.h[1]:a.hc;c=a.ta[16];b.gc=c?c.g[1]:a.gc;a.sa&&(c=a.sa.length-4,b.e[0]=a.sa[c],b.e[1]=a.sa[c+1],a.sa[c+2]&&(b.e[8]=a.sa[c+3]));b.ka=a.ka}function Ac(a,b){if(a.e[12]!=b){var c=new uc;c.e[0]=a.e[12];c.e[1]=b;a.ta[12]=c;a.ka|=4096;a.Ea|=4096}}
function Bc(a,b){var c={x:0,y:1,scaleX:2,scaleY:3,skewX:4,skewY:5,regX:6,regY:7,rotation:8,alpha:9,startPosition:10,playMode:11,_off:12,visible:13,loop:14,text:15,graphics:16},d=null,f=0,g;for(g in b){var h=b[g],k=new uc,l=c[g],f=f|1<<l;if(10>=l){var m=k,n=a.e[l];m.e[0]=n;m.e[1]=h;m.e[2]=h-n;a.dd=!1}else 11==l?(m=k,m.e[0]=a.e[l],m.e[1]="single"==h?1:"synched"==h?2:0):14>=l?(m=k,h=h|0,m.e[0]=a.e[l],m.e[1]=h):16==l?(d=h,k.g=[a.gc,d]):k.h=[a.hc,h];a.ta[l]=k}a.ka|=f;a.Ea|=f;if(c=b.guide){h=c.path;g=c.end;
k=c.orient;c=c.start||0;m=null==g?1:g;g=0;!k||f&256?(n=0,a.ka|=3,a.Ea|=3):(n={auto:2,cw:3,ccw:4}[k]||1,g=57.29577951308232*Math.atan2(h[3]-h[1],h[2]-h[0]),a.ka|=259,a.Ea|=259);a.dd=!1;for(var f=h.length-2>>2,p=0,k=[],s=0;s<f;++s){var v=s<<2,l=new yc(h,v,p);if(n){var v=l.J-l.h,w=l.$a-l.l,y=l.e-l.J,E=l.g-l.$a,x=0;if(1!=n)switch(x=57.29577951308232*Math.atan2(y,E)-57.29577951308232*Math.atan2(v,w),n){case 2:180<x?x-=360:-180>x&&(x+=360);break;case 3:0>x&&(x+=360);break;case 4:0<x&&(x-=360)}l.m=new wc(v,
w,y,E,x)}v=p;p=l;w=[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null];y=p.e-p.h;E=p.g-p.l;w[0]=new xc(p.h,p.l,0,0);w[16]=new xc(p.e,p.g,1,Math.sqrt(y*y+E*E));y=[0,16];do{var E=y.pop(),x=y.pop(),ka=w[E],Ka=w[x],la=.5*(Ka.fe+ka.fe),I=1-la,O=I*I,Wa=2*I*la,Dd=la*la,I=O*p.h+Wa*p.J+Dd*p.e,O=O*p.l+Wa*p.$a+Dd*p.g,Wa=I-Ka.C,Ka=O-Ka.D,la=new xc(I,O,la,Math.sqrt(Wa*Wa+Ka*Ka)),I=ka.C-I,O=ka.D-O,I=Math.sqrt(I*I+O*O),O=Math.abs(I-la.ua);(4<la.ua+I-ka.ua||4<O)&&4<=E-x&&(ka.ua=
I,ka=x+(E-x>>1),w[ka]=la,y.push(x,ka,ka,E))}while(0<y.length);O=I=y=0;for(E=1;17>E;++E)if(x=w[E])x.Wg=O,x.L=I,x.ua=x.ua,x.xa=(x.fe-O)/x.ua,I+=x.ua,O=x.fe,p.Fg[y]=x,++y;p.ua=I;p.uc=y;p=v+p.ua;k[s]=l}c*=p;m=m*p-c;h=[h[0],h[1],n,g];n=0;s=a.ze-1;for(p=1;p<s;++p)for(l=p*a.xa,a.ec&&(l=a.ec.R(l)),w=c+l*m,v=p<<2,y=n;y<f;++y)if(l=k[y],l.R(w,h,v,g)){n=y;break}l=k[f-1];l.Le(h,s<<2,g);a.sa=h}return d}
e.R=function(a,b){a-=this.L;var c=a*this.xa,d=this.ec?this.ec.R(c):c;if(this.sa){var f=a<<2;this.e[0]=this.sa[f];this.e[1]=this.sa[f+1];this.sa[f+2]&&(this.e[8]=this.sa[f+3])}if(this.Ea&1023)for(f=0;9>=f;++f){var g=this.ta[f];g&&(this.e[f]=g.e[0]+d*g.e[2])}if(this.Ea&130048){(g=this.ta[10])&&(this.e[10]=b||0==c||1==c?g.e[0]+c*g.e[2]:-1);for(f=11;14>=f;++f)(g=this.ta[f])&&(this.e[f]=g.e[d|0]);if(g=this.ta[15])this.hc=g.h[d|0];if(g=this.ta[16])this.gc=g.g[d|0]}return this.ka};
function Cc(a,b,c){return 4096==a.Ea?(a.e[12]=a.ta[12].e[(b-a.L)*a.xa|0],a.ka):a.R(b,c)};function Dc(a){for(var b=[],c=0;c<a;++c)b[c]=new vc;this.ic=b;this.uc=a}e=Dc.prototype;e.ic=null;e.uc=0;e.L=0;e.Sc=0;e.get=function(a){return this.ic[a]};function Ec(a,b){for(var c=0;c<a.uc;++c)zc(a.ic[c],b.ic[c])};function L(){Fc(this)}r(L,C);function Gc(a){this.h=[a];this.g=null;this.l=!1;this.m=this.e=-1}function Hc(a){if(!a.l)return a.h;a.g||(a.g=a.h.slice());return a.g}function Ic(){Bb.call(this)}r(Ic,Bb);e=Ic.prototype;e.Cf=null;e.nb=null;e.Xb=null;e.Fe=1;
function Jc(a,b){a.Xb||(a.Xb=new Ra);var c=a.Xb,d=b.e[0],f=b.e[1],g=b.e[2],h=b.e[3],k=a.e,l=k[0],m=k[3];if(0==(a.j&2)){var n=l*d,p=l*g;c.e[0]=u(n,p);c.e[2]=z(n,p);n=m*f;f=m*h;c.e[1]=u(n,f);c.e[3]=z(n,f)}else{var s=k[1],v=k[2],n=l*d+v*f,p=l*g+v*f,w=l*d+v*h,l=l*g+v*h;c.e[0]=u(u(u(n,p),w),l);c.e[2]=z(z(z(n,p),w),l);n=s*d+m*f;f=s*g+m*f;d=s*d+m*h;g=s*g+m*h;c.e[1]=u(u(u(n,f),d),g);c.e[3]=z(z(z(n,f),d),g)}g=k[4];k=k[5];c.e[0]+=g;c.e[2]+=g;c.e[1]+=k;c.e[3]+=k}e.V=function(){return 0<this.e[6]};var Kc=0;
L.prototype._off=!1;L.prototype.name="";L.prototype.zIndex=0;e=L.prototype;e.$e=0;e.S=null;e.k=0;e.Bg=!1;e.i=null;e.u=null;e.gb=0;e.Ma=null;e.Cc=null;e.Lb=null;e.Wd=null;e.oe=null;e.me=null;e.ke=null;e.T=null;e.oa=!1;e.qe=!1;e.Y=-1;e.W=null;e.sd=null;function Fc(a){a.$e=Kc++;a.S=new Ic;a.i=A([0,0,1,1,0,0,0,0,0,1,0,0,0,1,1]);a.u=new Ra}e.Mi=null;e.Zc=function(){return this.i[0]};e.Lf=function(a){a===a&&this.i[0]!=a&&(this.i[0]=a,this.k|=9)};e.nc=function(){return this.i[1]};
e.Mf=function(a){a===a&&this.i[1]!=a&&(this.i[1]=a,this.k|=9)};e.pe=function(){return this.i[2]};e.td=function(a){this.i[2]!=a&&(this.i[2]=a,this.k|=9)};e.Df=function(){return this.i[3]};e.ud=function(a){this.i[3]!=a&&(this.i[3]=a,this.k|=9)};e.kh=function(){return this.i[4]};e.Jf=function(a){this.i[4]!=a&&(this.i[4]=a,this.k|=9)};e.lh=function(){return this.i[5]};e.Kf=function(a){this.i[5]!=a&&(this.i[5]=a,this.k|=9)};e.gh=function(){return this.i[6]};
e.Gf=function(a){this.i[6]!=a&&(this.i[6]=a,this.k|=9)};e.hh=function(){return this.i[7]};e.Hf=function(a){this.i[7]!=a&&(this.i[7]=a,this.k|=9)};e.ih=function(){return this.i[8]};e.If=function(a){this.i[8]!=a&&(this.i[8]=a,this.k|=9)};e.mh=function(){return!!this.i[13]};e.qh=function(a){a=a|0;this.i[13]!=a&&(this.i[13]=a,this.k=31)};e.dh=function(){return this.i[9]};e.oh=function(a){this.i[9]!=a&&(this.i[9]=a,this.k|=a?2:31)};e.jh=function(){return this.Ma};
e.Rg=function(a){if(!this.Ma||this.Ma.color!=a.color&&this.Ma.g!=a.g&&this.Ma.h!=a.h&&this.Ma.e!=a.e)this.Ma=a,this.k|=2};e.eh=function(){return Na(this.gb)};e.Ff=function(a){a={"source-over":0,"source-atop":1,"source-in":2,"source-out":3,"destination-over":4,"destination-atop":5,"destination-in":6,"destination-out":7,lighter:8,copy:9,xor:10,darker:11}[a]||0;this.gb!=a&&(this.gb=a,this.k|=2)};e.mi=function(){return[]};
e.Qi=function(a){for(var b=null,c=null,d=a.length-1;0<=d;--d){var f=a[d],g=f.e;3==g?(c=f.l,f=f.g,c=new Float32Array([c.h,0,0,0,f.h,0,c.g,0,0,f.g,0,0,c.e,0,f.e,0,0,0,1,0,0,0,0,0,1])):0==g?b=f:4==g&&(c=f.h.Yg())}if(this.ke!==b||this.me!==c)this.ke=b,this.me=c,this.k|=4,this.fa(),this.ib(1)};e.fh=function(){return this.Cc};
e.Si=function(a){a._off=!1;a.Lb||(a.Lb=[]);for(var b=0;b<a.Lb.length;++b)if(a.Lb[b]===this)return;a.Lb.push(this);a.gb=2;a.S.e[7]=6;this.gb=0;a.ib(2);this.Cc=a;this.oe=null;this.k|=8};function Lc(a){return(a.zIndex<<10)+(a.nc()|0)}function Mc(a){a.Wd||(a.Wd=Cb(a.S));return a.Wd}function M(a,b,c,d,f){if(a.u.e[0]!=b||a.u.e[1]!=c||a.u.e[2]!=d||a.u.e[3]!=f)a.u.e[0]=b,a.u.e[1]=c,a.u.e[2]=d,a.u.e[3]=f,a.k|=16}e.cf=function(){return null};e.df=function(){return null};e.Ef=function(){return!1};e.Jg=function(){return!1};
e.na=function(){};e.ib=function(){};e.fa=function(){};e.za=function(a,b,c){c|=b&this.Ya;if(!c)return null;c=this.S;b=c.nb;var d;b?d=b.g:(c.Fe&&(Jc(c,this.u),c.Fe=0),d=c.Xb);if(!this.V()||!d.h(a.e[0],a.e[1]))return null;c=b?b.m:c;if(c.j&2){b=b?b.l:this.u;if(!c.g||b.g())return null;a=new F(a.e[0],a.e[1]);Db(Cb(c),a);if(!b.h(a.e[0],a.e[1]))return null}return this};e.Me=function(a,b,c,d){(a=this.za(a,c,d))&&b.push(a)};
function Nc(a,b,c){var d=a.S;if(c&9){var f=b.S;d.set(a.i);var g=d.e,h=g[0],k=g[1],l=g[2],m=g[3],n=g[4],p=g[5],s=f.e,v=s[0],w=s[1],y=s[2],E=s[3],x=s[4],s=s[5];d.j?(g[0]=v*h+y*k,g[1]=w*h+E*k,g[2]=v*l+y*m,g[3]=w*l+E*m):(g[0]=v,g[1]=w,g[2]=y,g[3]=E,d.j=f.j);g[4]=v*n+y*p+x;g[5]=w*n+E*p+s;a.Wd=null}c&2&&(f=b.S,g=a.Ma,h=a.gb,d.e[6]=f.e[6]*a.i[9],d.Cf=g||f.Cf,d.e[7]=h||f.e[7]);c&8&&(a.Cc&&!a.Cc.u.g()&&(c=a.Cc,Nc(c,b,9),Jc(c.S,c.u),a.oe=new Oa(c.S,c.u,c.S.Xb,c.gb,c)),d.nb=a.oe||b.S.nb)}
e.ga=function(a,b,c){var d=this.S;if(!this.V())return 0;if(c|=this.k)Nc(this,b,c),d.Fe=c&25;a.nd(this);return this.Ya};function Xa(a,b){a.k=0;b.Cd(a.S.e)}e.va=function(){};e.V=function(){var a=this.i[9],b=this.i[2],c=this.i[3];return this.i[13]&&a&&b&&c?!0:!1};e.yg=function(){for(var a=this;a.parent;)a=a.parent;return a.Bg?a:null};e.Qe=function(a,b){var c=new F(a,b);return Db(this.S,c)};e.Gi=function(a,b){var c=new F(a,b);return Db(Mc(this),c)};
e.Li=function(a,b,c){a=this.Qe(a,b);return Db(Mc(c),a)};e.ph=function(a,b,c,d,f,g,h,k,l){this.Lf(a||0);this.Mf(b||0);this.td(null==c?1:c);this.ud(null==d?1:d);this.Jf(g||0);this.Kf(h||0);this.Gf(k||0);this.Hf(l||0);this.If(f||0);return this};e.nh=function(a,b){return!!this.za(new F(a,b),0,1)};
e.set=function(a){var b={x:1,y:2,scaleX:3,scaleY:4,skewX:5,skewY:6,regX:7,regY:8,rotation:9,alpha:10},c=0,d;for(d in a){var f=a[d];if("_off"==d)Oc(this,!!f);else if("compositeOperation"==d)this.Ff(f);else{var g=b[d];g&&(--g,f=+f,this.i[g]!=f&&(this.i[g]=f,c=1<<g))}}c&511&&(this.k|=9);c&512&&(this.k|=this.i[9]?2:31);c&8192&&(this.k|=31);return this};
e.Za=function(){var a=this.u.e[0],b=this.u.e[1],c=Pa(this.u),d=Qa(this.u);if(this.sd){var f=this.sd;f.x=a;f.y=b;f.width=c;f.height=d}else this.sd=new G(a,b,c,d);return this.sd};e.Ig=function(a){if(this.T){for(var b=Hc(this.T),c=b.length-1;0<=c;--c)if(b[c]===a)return;b.unshift(a)}else this.T=new Gc(a);this.oa=!1};function Pc(a){if(a.T){for(var b=Hc(a.T),c=b.length-1;0<=c;--c)Qc(b[c],0);a.T=null}a.W=null}function Rc(a,b){if(a.oa||a.W)if(a.oa=!1,a.W)for(var c=0;c<a.W.length;++c)Rc(a.W[c],b)}
function Sc(a,b){if(!a.oa&&(a.oa=!0,a.W))for(var c=0;c<a.W.length;++c)Sc(a.W[c],b)}e.Sb=function(a){if(this.T&&this.T.h.length&&(!this.oa||this.qe)){this.qe=!1;var b=this.T,c=this.i[11],d;b.l=!0;d=b.h;var f=d.length,g=-1;0<=b.e&&2==c&&(c|=4);for(var h=f-1;0<=h;--h){var k=b.e,g=Tc(d[h],a,c,b.e);if(b.e!=k)for(c|=4,k=f-1;k>=h;--k)d[k].Gd(b.e,1)}b.l=!1;b.g&&(b.h=b.g,b.g=null);b.e=-1;b.m=a;this.Y=g}};
function Uc(a,b){if(a.T){var c=a.T,d=Vc();if(c.l||!a.oa&&c.m<d)c.e=b;else{for(var d=Hc(c),f=d.length-1;0<=f;--f)d[f].Gd(b,1);c.e=-1}}if(a.W)for(c=0;c<a.W.length;++c)Uc(a.W[c],b);a.qe=!0}function Oc(a,b){a._off!=b&&(a._off=b,a.i[12]=b|0,a.k=31,b&&Uc(a,0))}function Wc(a,b,c){if(a.W)for(var d=0;d<a.W.length;++d){if(a.W[d]===b){c||a.W.splice(d,1);return}}else{if(!c)return;a.W=[]}a.W.push(b)}e.ff=function(){};
e.mc=function(a){if(!this.i)return!1;this.i[12]=this._off|0;for(var b=0;14>=b;++b)a.e[b]=this.i[b];return!0};e.ya=function(a,b){if(b){for(var c=9,d=0;8>=d;++d)b&1<<d&&(this.i[d]=a.e[d]);b&512&&(d=a.e[9],this.i[9]!=d&&(c|=d?2:31,this.i[9]=d));b&4096&&Oc(this,!!a.e[12]);b&8192&&(d=a.e[13],this.i[13]!=d&&(c|=31,this.i[13]=d));this.k|=c}};
Object.defineProperties(L.prototype,{x:{get:L.prototype.Zc,set:L.prototype.Lf},y:{get:L.prototype.nc,set:L.prototype.Mf},scaleX:{get:L.prototype.pe,set:L.prototype.td},scaleY:{get:L.prototype.Df,set:L.prototype.ud},skewX:{get:L.prototype.kh,set:L.prototype.Jf},skewY:{get:L.prototype.lh,set:L.prototype.Kf},regX:{get:L.prototype.gh,set:L.prototype.Gf},regY:{get:L.prototype.hh,set:L.prototype.Hf},rotation:{get:L.prototype.ih,set:L.prototype.If},visible:{get:L.prototype.mh,set:L.prototype.qh},alpha:{get:L.prototype.dh,
set:L.prototype.oh},shadow:{get:L.prototype.jh,set:L.prototype.Rg},compositeOperation:{get:L.prototype.eh,set:L.prototype.Ff},filters:{get:L.prototype.mi,set:L.prototype.Qi},mask:{get:L.prototype.fh,set:L.prototype.Si},stage:{get:L.prototype.yg}});
t("createjs.DisplayObject",L,{nominalBounds:L.prototype.Mi,cache:ea,updateCache:ea,uncache:ea,getCacheDataURL:ea,getStage:L.prototype.yg,localToGlobal:L.prototype.Qe,globalToLocal:L.prototype.Gi,localToLocal:L.prototype.Li,setTransform:L.prototype.ph,hitTest:L.prototype.nh,set:L.prototype.set,getScaleX:L.prototype.pe,setScaleX:L.prototype.td,getScaleY:L.prototype.Df,setScaleY:L.prototype.ud,getBounds:L.prototype.Za,setBounds:ea});function N(){Fc(this);this.q=new Xc}r(N,L);function Xc(){this.g=[];this.e=null;this.h=!1}function P(a){if(!a.h)return a.g;a.e||(a.e=a.g.slice());return a.e}function Yc(a){a.h=!0;return a.g}function Zc(a){a.h=!1;a.e&&(a.g=a.e,a.e=null)}function $c(a,b){for(var c=P(a),d=c.length-1;0<=d;--d)if(c[d]===b){c.splice(d,1);break}}e=N.prototype;e.q=null;e.fb=null;e.yc=0;function ad(a,b){var c=b.parent;c?(b.parent=null,$c(c.q,b)):b.ib(1);b.k=31;b.parent=a}e.ii=function(a){return P(this.q)[a]};
e.ji=function(a){for(var b=P(this.q),c=b.length-1;0<=c;--c){var d=b[c];if(d.name==a)return d}return null};function bd(a,b){return Lc(a)-Lc(b)}e.Yi=function(){Vc();var a=P(this.q),b=a.length;if(b)for(var c=Lc(a[0]),d=1;d<b;++d){var f=Lc(a[d]);if(c>f){a.sort(bd);break}c=f}};e.ki=function(a){for(var b=P(this.q),c=b.length-1;0<=c;--c)if(b[c]===a)return c;return-1};e.vi=function(){return P(this.q).length};e.li=function(){if(!this.fb){var a=this.q;this.fb=(a.e?a.e:a.g).slice()}return this.fb};
e.$i=function(a,b){if(0<=a&&0<=b){var c=P(this.q),d=c.length;a<d&&b<d&&(d=c[a],c[a]=c[b],c[b]=d)}};e.Zi=function(a,b){if(a.parent===this&&b.parent===this){for(var c=P(this.q),d=-1,f=-1,g=c.length-1;0<=g;--g){var h=c[g];h===a?d=g:h===b&&(f=g)}0<=d&&0<=f&&(c[d]=b,c[f]=a)}};e.Pi=function(a,b){if(0<=b&&a.parent===this){for(var c=P(this.q),d=c.length-1;0<=d;--d)if(c[d]===a){c.splice(d,1);break}c.splice(b,0,a)}};e.yi=function(a,b){var c=[];this.Me(this.Qe(a,b),c,0,1);return c};
e.xi=function(a,b){return this.za(new F(a,b),0,1)};e.cf=function(a){var b=arguments,c=b.length;if(1>c)return null;for(var d=P(this.q),f=0;f<c;++f){var g=b[f];ad(this,g);d.push(g)}this.fb=null;return b[c-1]};e.df=function(a){var b=arguments,c=b.length;if(2>c)return null;var d=P(this.q),f;f=b[--c];for(var g=0;g<c;++g,++f){var h=b[g];ad(this,h);d.splice(f,0,h)}this.fb=null;return b[c-1]};
e.Ef=function(a){var b=arguments,c=b.length;if(1>c)return!1;for(var d=0;d<c;++d){var f=b[d],g=f;g.parent=null;g.Pb();$c(this.q,f);f.fa()}this.fb=null;return!0};e.Jg=function(a){var b=arguments,c=b.length;if(1>c)return!1;for(var d=0;d<c;++d){var f=b[d];if(0<=f){var g=P(this.q);if(f<g.length){var h=g[f],k=h;k.parent=null;k.Pb();g.splice(f,1);h.fa()}}}this.fb=null;return!0};
e.na=function(){if(this.q){for(var a=P(this.q),b=a.length-1;0<=b;--b){var c=a[b];c&&(c.na(!0),c.parent=null,c.Pb())}a=this.q;a.h?a.e=[]:a.g=[]}this.fb=null};e.fa=function(){if(this.q)for(var a=P(this.q),b=a.length-1;0<=b;--b){var c=a[b];c.k=31;c.fa()}};e.za=function(a,b,c){c|=b&this.Ya;if(c|b&this.yc)for(var d=P(this.q),f=d.length-1;0<=f;--f){var g=d[f];if(!g._off&&g.V()&&(g=g.za(a,b,c)))return g}return null};
e.Me=function(a,b,c,d){d|=c&this.Ya;if(d|c&this.yc)for(var f=P(this.q),g=f.length-1;0<=g;--g){var h=f[g];!h._off&&h.V()&&h.Me(a,b,c,d)}};e.ga=function(a,b,c,d,f){this.yc=this.Ya;c|=this.k;Nc(this,b,c);b=Yc(this.q);for(var g=b.length,h=0;h<g;++h){var k=b[h];k._off?k.k=31:(k.Sb(d),k.V()&&(this.yc|=k.ga(a,this,c,d,f)))}Zc(this.q);this.k=0;return this.yc};
e.Za=function(){if(this.u.g()){for(var a=Yc(this.q),b=1E4,c=1E4,d=-1E4,f=-1E4,g=a.length-1;0<=g;--g)var h=a[g],k=h.Za(),l=k.x+h.Zc(),h=k.y+h.nc(),b=u(b,l),c=u(c,h),d=z(d,l+k.width),f=z(f,h+k.height);Zc(this.q);if(b>d||c>f)return null;M(this,b,c,d,f)}return N.B.Za.call(this)};Object.defineProperties(N.prototype,{children:{get:N.prototype.li}});
t("createjs.Container",N,{addChild:N.prototype.cf,addChildAt:N.prototype.df,removeChild:N.prototype.Ef,removeChildAt:N.prototype.Jg,removeAllChildren:N.prototype.na,getChildAt:N.prototype.ii,getChildByName:N.prototype.ji,sortChildren:N.prototype.Yi,getChildIndex:N.prototype.ki,getNumChildren:N.prototype.vi,swapChildrenAt:N.prototype.$i,swapChildren:N.prototype.Zi,setChildIndex:N.prototype.Pi,getObjectsUnderPoint:N.prototype.yi,getObjectUnderPoint:N.prototype.xi,getBounds:N.prototype.Za});function cd(a){Fc(this);this.ea=a?a:new K}r(cd,L);e=cd.prototype;e.ea=null;e.Ja=null;e.bc=null;e.Yf=null;e.Lh=function(){return this.ea};e.xe=function(a){var b=this.Lb;if(b&&this.gb&&(this.ea=a))for(a=a.A,M(this,a.e[0],a.e[1],a.e[2],a.e[3]),a=0;a<b.length;++a)b[a].k|=8};e.ib=function(a){var b=this.ea;if(a&&(sc(b,a),a&2&&this.Ja))for(var c=0;c<this.Ja.length;++c)sc(this.Ja[c],a);a=b.A;M(this,a.e[0],a.e[1],a.e[2],a.e[3])};e.na=function(){this.fa()};
e.fa=function(){this.ea&&(tc(this.ea),this.ea=null);if(this.Ja){for(var a=0;a<this.Ja.length;++a)tc(this.Ja[a]);this.Ja=null}};
e.za=function(a,b,c){if((b=L.prototype.za.call(this,a,b,c))&&this.ea){if(this.bc){c=this.bc.e[0]-a.e[0];var d=this.bc.e[1]-a.e[1];if(4>=c*c+d*d)return this.Yf;this.bc.e[0]=a.e[0];this.bc.e[1]=a.e[1]}else this.bc=new F(a.e[0],a.e[1]);d=new F(a.e[0],a.e[1]);Db(Mc(this),d);var f=this.ea;if(a=f.Ba)a=f.Ba,c=d.e[0]-f.A.e[0],d=d.e[1]-f.A.e[1],(f=a.e)?(c*=a.Ec,d*=a.Fc,a=f.getImageData(c|0,d|0,1,1).data[3]):a=0;a||(b=null);this.Yf=b}return b};
e.ga=function(a,b,c,d,f){var g=this.ea;if(!g)return 0;if(g.j||g.gd)this.k|=4,g=g.A,M(this,g.e[0],g.e[1],g.e[2],g.e[3]);return cd.B.ga.call(this,a,b,c,d,f)};e.va=function(a){var b=this.ea;sc(b,0);b.Ba&&(b.Ba.vd=a,a.Xc(b.Ba.g,b.Yb))};e.V=function(){var a;if(a=!!this.ea)a=this.ea,a=!(!a.Aa.length&&!a.N.length);return a&&cd.B.V.call(this)};e.set=function(a){cd.B.set.call(this,a);(a=a.graphics)&&this.xe(a);return this};e.ff=function(a){a&&(this.Ja||(this.Ja=[]),this.Ja.push(a))};
e.mc=function(a){if(!cd.B.mc.call(this,a))return!1;a.gc=this.ea;return!0};e.ya=function(a,b,c){b&65536&&this.xe(a.gc);cd.B.ya.call(this,a,b,c)};Object.defineProperties(cd.prototype,{graphics:{get:cd.prototype.Lh,set:cd.prototype.xe}});t("createjs.Shape",cd,{});function Q(a){N.call(this);this.U=dd(a);this.sc=[];this.qg(!0)}r(Q,N);var ed=[["mousedown","mousemove","mouseup"],["touchstart","touchmove","touchend"],["pointerstart","pointermove","pointerend"]];function fd(a){this.id=a;this.l=new F(-1,-1);this.g=new F(0,0);this.h=!1;this.e=null;this.m=new F(0,0)}Q.prototype.mouseX=0;Q.prototype.mouseY=0;Q.prototype.mouseInBounds=!1;e=Q.prototype;e.U=null;e.sc=null;e.cd=null;e.Mb=-2;e.Xa=0;e.Gg=!1;
function dd(a){if(!a)return null;ga(a)&&(a=document.getElementById(a));a.setAttribute("dena-version","0.9.0.0");var b={antialias:!1,depth:!1};if(!bb){bb=1;for(var c=["webgl","experimental-webgl"],d=0;d<c.length;++d){var f=a.getContext(c[d],b);if(f)return ab=c[d],new Za(a,f,null)}}return ab?(f=a.getContext(ab,b),new Za(a,f,null)):new Ta(a,null)}function gd(a,b,c){if(a.cd){var d=a.cd;d.nativeEvent=b;d.pointerID=c}else a.cd=new Ab("",0,0,0,0,b,c,!1,0,0);return a.cd}
function hd(a,b,c){if(a=a.cd)c=c||a.Dc,a.Dc=!1,a.Yd&&b.stopPropagation(),a.Yd=!1;c&&b.preventDefault()}e.Rh=function(){return this.U.X};e.Oi=function(a){var b=this.U;if(b){var c=b.X;c&&(id(this,c,0),id(this,c,1),id(this,c,2));b.Hc();this.U=null}this.U=dd(a)};function jd(a,b,c){for(var d=0;d<a.sc.length;++d)if(a.sc[d].id==b){var f=a.sc[d];c&&0<=b&&a.sc.splice(d,1);return f}f=new fd(b);a.sc.push(f);return f}
function kd(a,b,c,d,f){if(!(4>=ha(b.l.e[0]-c)&&4>=ha(b.l.e[1]-d))){b.l.e[0]=c;b.l.e[1]=d;var g=a.U,h=g.X,k=g.qa,g=g.pa,l=h.getBoundingClientRect(),m=window.pageXOffset-document.body.clientLeft,n=window.pageYOffset-document.body.clientTop,h=window.getComputedStyle(h),p=l.left+m+(h.paddingLeft|0)+(h.borderLeftWidth|0),s=l.top+n+(h.paddingTop|0)+(h.borderTopWidth|0),n=l.bottom+n-(h.paddingBottom|0)-(h.borderBottomWidth|0);c=(c-p)/(l.right+m-(h.paddingRight|0)-(h.borderRightWidth|0)-p)*k;d=(d-s)/(n-s)*
g;if(g=0<=c&&c<k&&0<=d&&d<g)b.g.e[0]=c,b.g.e[1]=d;b.h=g;b.m.x=c;b.m.y=d;if(k=b.id==a.Mb)a.mouseX=c,a.mouseY=d,a.mouseInBounds=g;a=b.g.e[1];f.stageX=b.g.e[0];f.stageY=a;f.primary=k;a=b.m.e[1];f.rawX=b.m.e[0];f.rawY=a}}function ld(a,b,c,d,f){f=gd(a,f,b);b=jd(a,b);kd(a,b,c,d,f);f.e="stagemousedown";f.Na=!1;b.h&&a.ba(f.e)&&D(a,f);if(a=a.za(b.g,3,0))f.e="mousedown",f.Na=!0,D(a,f);f.Dc||(b.e=a)}
function md(a,b,c,d,f){f=gd(a,f,b);var g=jd(a,b),h=g.h;kd(a,g,c,d,f);if(h||g.h)-1==b&&g.h==!h&&(f.e=h?"mouseleave":"mouseenter",f.Na=!1,a.ba(f.e)&&D(a,f)),f.e="stagemousemove",f.Na=!1,a.ba(f.e)&&D(a,f),g.e&&(f.e="pressmove",f.Na=!0,D(g.e,f))}function nd(a,b,c){c=gd(a,c,b);b=jd(a,b,!0);c.e="stagemouseup";c.Na=!1;a.ba(c.e)&&D(a,c);b.e&&(a=a.za(b.g,9,0),a==b.e&&(c.e="click",c.Na=!0,D(a,c)),c.e="pressup",c.Na=!0,D(b.e,c),c.e="mouseup",D(b.e,c),b.e=null)}
function od(a,b,c){var d=1<<c;if(!(a.Xa&d))for(a.Xa|=d,c=ed[c],d=0;d<c.length;++d)b.addEventListener(c[d],a,!1)}function id(a,b,c){a.Xa&=~(1<<c);c=ed[c];for(var d=0;d<c.length;++d)b.removeEventListener(c[d],a,!1)}e.Sh=function(){this.U&&this.U.X&&this.oc(Vc())};e.qg=function(a){if(this.U){var b=this.U.X;b&&(a?(od(this,b,0),window.addEventListener("hashchange",this,!1),window.addEventListener("unload",this,!1)):id(this,b,0))}};
function pd(a,b,c){if(a.U){var d=a.U.X;b?(a.Gg=c,1==Aa().e?od(a,d,2):od(a,d,1),Ba(3)&&id(a,d,0)):(id(a,d,1),id(a,d,2))}}e.Bg=!0;e.na=function(a){Q.B.na.call(this);hc=[null,null,null,null];kc=0;mc={};var b=oc,c;for(c in b){var d=b[c];d&&Fb(d)}oc={};qd(a);(b=Fa)?(c=b.e,a&&(b.e={}),b=c):b=null;if(c=this.U){if(b){a=a&&Ba(4);for(var f in b)if(d=b[f])c.rb(d),a&&(d.src="data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs=")}c.Hc()}};
e.oc=function(a){this.U&&(this.Sb(a),this.U.le(),this.ga(this.U,this,this.k,a,1),this.U.Jc(a))};
e.handleEvent=function(a){if(2==Aa().e&&ra(a,this.Xa))rd();else{var b=a.type,c=!1;if(this.Xa&2)if("touchstart"==b){var c=!0,d=a.changedTouches;-2==this.Mb&&(this.Mb=d[0].identifier||0);for(var f=0;f<d.length;++f){var g=d[f],h=g.identifier||f;ld(this,h,g.pageX,g.pageY,a)}}else if("touchmove"==b)for(c=!0,d=a.changedTouches,f=0;f<d.length;++f)g=d[f],h=d[f].identifier||f,md(this,h,g.pageX,g.pageY,a);else{if("touchend"==b)for(c=!0,d=a.changedTouches,f=0;f<d.length;++f)g=d[f],h=g.identifier||f,nd(this,
h,a),this.Mb==h&&(this.Mb=-2)}else this.Xa&4&&(d=a.pageX,f=a.pageY,"pointerdown"==b?(c=!0,a.isPrimary&&(this.Mb=a.pointerId),ld(this,a.pointerId,d,f,a)):"pointermove"==b?(c=!0,md(this,a.pointerId,d,f,a)):"pointerup"==b&&(nd(this,a.pointerId,a),c=!0));if(c)hd(this,a,this.Gg),rd();else if("hashchange"==b||"unload"==b){if(window.removeEventListener(b,this,!1),this.na(!0),"unload"==b){a=R();for(var k in a.e)(b=a.e[k])&&b.ha();if(k=sd)k.stop?k.stop(0):k.noteOff(0),k.disconnect(0),sd=null;td=null;ud=!1}}else d=
a.pageX,f=a.pageY,this.Xa&1&&("mousedown"==b?(this.Mb=-1,ld(this,-1,d,f,a)):"mousemove"==b?md(this,-1,d,f,a):"mouseup"==b&&nd(this,-1,a),hd(this,a,!1))}};Object.defineProperties(Q.prototype,{canvas:{get:Q.prototype.Rh,set:Q.prototype.Oi}});t("createjs.Stage",Q,{update:Q.prototype.Sh,clear:ea,toDataURL:da,enableMouseOver:da,enableDOMEvents:Q.prototype.qg,handleEvent:Q.prototype.handleEvent});function S(a,b,c){Fc(this);this.ia=a;this.Qa=b;this.wc=c;this.cc=A([0,0,0,0])}r(S,L);function vd(){this.Ca=ia();this.G=this.Ca.getContext("2d");this.Ca.Eb=1}e=vd.prototype;e.Ca=null;e.G=null;e.bg=0;e.ag=0;e.Fd="";function wd(a,b){a.Fd!=b&&(a.Fd=b,a.G.font=b)}var xd={};e=S.prototype;e.ia="";e.Qa="";e.wc="";e.cc=null;e.vc="left";e.ge="top";e.bd=0;e.Kb=0;e.Xd=0;e.Pc=0;e.da=!0;e.ab=null;e.Hb=0;e.ja=0;e.ub=0;e.Ra=null;e.Qc=null;function yd(a){a.Ra||(a.Ra=new vd);return a.Ra}
function zd(a){a.da=!1;var b=yd(a);if(!a.ab){wd(b,a.Qa);var c;c=a.ia.split("\n");var d=a.bd;if(0<d)a.ja=d;else{var f=c.length;if(0>=a.Pc){for(var g=d=0;g<f;++g)var h=b.G.measureText(c[g]).width,d=z(h,d);a.ja=d}else{a.ja=a.Pc/a.pe();for(var d=a.ja,k=[],g=0;g<f;++g){var l=c[g],h=b.G.measureText(l).width;if(h<=d)k.push(l);else{var m,h=l;m=[];for(var n=0,p=h.charCodeAt(0),s=1;s<h.length;++s){var v=h.charCodeAt(s);if(32>=v)s>=n&&m.push(h.substring(n,s)),n=s;else{var w;if(w=12288<=v&&44032>v){w=p&255;if(p=
48==p>>8?0==([89216256,0,0,0,0,0,0,0][w>>5]&1<<(w&31)):!0)p=v>>8,w=v&255,p=32!=p&&48==p?0==([178432518,0,682,8,168,682,8,268435624][w>>5]&1<<(w&31)):!0;w=p}w&&(s>=n&&m.push(h.substring(n,s)),n=s)}p=v}n<h.length&&m.push(h.substring(n));if(1==m.length)k.push(l);else{h=0;l="";for(n=0;n<m.length;++n)s=b.G.measureText(m[n]).width,h+=s,h>d?(k.push(l),l=m[n],h=s):l+=m[n];l&&k.push(l)}}}c=k}}a.ab=c}c=a.ab;d=c.length;a.Hb=a.Xd||a.wg();f=a.Hb;a.ub=(d+.5)*f;g=0;a.Kb&&(g=a.Kb);(k=a.Ma)&&(g=z(g,z(ha(k.g),ha(k.h))+
k.e));l=g<<1;a.ja+=l;a.ub+=l;l=a.ja;h=a.ub;b.bg!=l&&(b.bg=l,b.Ca.width=l,b.Fd="");b.ag!=h&&(b.ag=h,b.Ca.height=h,b.Fd="");wd(b,a.Qa);b.G.textAlign=a.vc;b.G.textBaseline=a.ge;k?(b.G.shadowColor=k.color,b.G.shadowOffsetX=k.g,b.G.shadowOffsetY=k.h,b.G.shadowBlur=k.e):(b.G.shadowColor="#000",b.G.shadowOffsetX=0,b.G.shadowOffsetY=0,b.G.shadowBlur=0);b.G.clearRect(0,0,a.ja,a.ub);b.Ca.j=!0;k=g;"center"==a.vc?k=a.ja>>1:"right"==a.vc&&(k=a.ja);a.cc[0]=-k;a.cc[1]=-g;a.cc[2]=a.ja;a.cc[3]=a.ub;l=a.bd||1E4;if(a.Kb)for(b.G.strokeStyle=
a.wc,b.G.lineWidth=a.Kb,h=0;h<d;++h)b.G.strokeText(c[h],k,g,l),g+=f;else for(b.G.fillStyle=a.wc,h=0;h<d;++h)b.G.fillText(c[h],k,g,l),g+=f;M(a,-k,-g,a.ja-k,a.ub-g)}e.Uh=function(){return this.ia};e.dg=function(a){a=null==a?"":a+"";this.ia!=a&&(this.ia=a,this.ab=null,this.da=!0)};e.ni=function(){return this.ia};e.Mg=function(a){this.Qa!=a&&(this.Qa=a,this.Hb=0,this.da=!0)};e.Th=function(){return this.wc};e.cg=function(a){a=a||"#000";this.wc!=a&&(this.wc=a,this.da=!0)};e.Ei=function(){return this.vc};
e.Tg=function(a){a=a||"left";this.vc!=a&&(this.vc=a,this.da=!0)};e.Fi=function(){return this.ge};e.Ug=function(a){a=a||"top";this.ge!=a&&(this.ge=a,this.da=!0)};e.si=function(){return this.bd};e.Pg=function(a){this.bd!=a&&(this.bd=a,this.ab=null,this.da=!0)};e.zi=function(){return this.Kb};e.Qg=function(a){this.Kb!=a&&(this.Kb=a,this.da=!0)};e.qi=function(){return this.Xd};e.Ng=function(a){this.Xd!=a&&(this.Xd=a,this.da=!0)};e.ri=function(){return this.Pc};
e.Og=function(a){this.Pc!=a&&(this.Pc=a,this.ab=null,this.da=!0)};e.xg=function(){this.da&&this.ia&&zd(this);return this.ja};e.wg=function(){if(!this.Hb){if(!xd[this.Qa]){var a=yd(this);wd(a,this.Qa);xd[this.Qa]=1.2*a.G.measureText("M").width}this.Hb=xd[this.Qa]}return this.Hb};e.ti=function(){this.da&&this.ia&&zd(this);return this.Hb*(this.ab?this.ab.length:0)};e.V=function(){return!!this.ia&&S.B.V.call(this)};e.ib=function(){};e.na=function(){this.fa();this.ia=""};
e.fa=function(){this.Qc&&this.Ra&&this.Qc.rb(this.Ra.Ca);this.Qc=null;if(this.Ra){var a=this.Ra;a.Ca&&(a.Ca.width=0,a.G=null,a.Ca=null)}this.Ra=null;this.da=!0};e.ga=function(a,b,c,d,f){this.da&&f&&(this.k|=4,zd(this));this.Qc||(this.Qc=a);return S.B.ga.call(this,a,b,c,d,f)};e.va=function(a){a.Xc(this.Ra.Ca,this.cc)};
e.set=function(a){S.B.set.call(this,a);var b={text:S.prototype.dg,font:S.prototype.Mg,color:S.prototype.cg,textAlign:S.prototype.Tg,textBaseline:S.prototype.Ug,maxWidth:S.prototype.Pg,outline:S.prototype.Qg,lineHeight:S.prototype.Ng,lineWidth:S.prototype.Og,shadow:S.prototype.Rg},c;for(c in a){var d=b[c];d&&d.call(this,a[c])}return this};e.Za=function(){if(this.u.g()){var a=this.xg();M(this,0,0,a,0)}return S.B.Za.call(this)};e.mc=function(a){if(!S.B.mc.call(this,a))return!1;a.hc=this.ia;return!0};
e.ya=function(a,b,c){if(b&32768){var d=a.hc;this.ia!=d&&(this.ia=d,this.ab=null,this.da=!0)}S.B.ya.call(this,a,b,c)};
Object.defineProperties(S.prototype,{text:{get:S.prototype.Uh,set:S.prototype.dg},font:{get:S.prototype.ni,set:S.prototype.Mg},color:{get:S.prototype.Th,set:S.prototype.cg},textAlign:{get:S.prototype.Ei,set:S.prototype.Tg},textBaseline:{get:S.prototype.Fi,set:S.prototype.Ug},maxWidth:{get:S.prototype.si,set:S.prototype.Pg},outline:{get:S.prototype.zi,set:S.prototype.Qg},lineHeight:{get:S.prototype.qi,set:S.prototype.Ng},lineWidth:{get:S.prototype.ri,set:S.prototype.Og}});
t("createjs.Text",S,{getMeasuredWidth:S.prototype.xg,getMeasuredLineHeight:S.prototype.wg,getMeasuredHeight:S.prototype.ti});function Ad(a){if(a){this.ug=a.framerate||0;if(a.images){this.Oc=[];for(var b=a.images,c=b.length,d=0;d<c;++d){var f;f=b[d];ga(f)&&(f=Ga(f,f,this,1));this.Oc.push(f);f.complete||(++this.Pe,this.complete=!1)}}if(a.frames)if(a.frames instanceof Array)for(this.ra=[],b=a.frames,c=b.length,d=0;d<c;++d){var g=b[d],h=g[0],k=g[1],l=g[2],m=g[3];f=this.Oc[g[4]?g[4]:0];this.ra.push(new Bd(f,new G(h,k,l,m),g[5]||0,g[6]||0,l,m))}else this.Yc=a.frames,this.Se=this.Yc.count||0,this.Pe||Cd(this);this.od=[];if(a=
a.animations){this.Db={};for(var n in a){d=c=new Ed(n);f=n;b=a[n];if("number"==typeof b)d.e=[b];else if(b instanceof Array)if(1==b.length)d.e=[b[0]];else{d.e=[];g=b[1];for(h=b[0];h<=g;++h)d.e.push(h);b[2]&&(d.g=f);d.h=b[3]||1}else d.h=b.speed||1,d.g=b.next||"",b=b.frames,d.e="number"==typeof b?[b]:b.slice(0);2>d.e.length&&d.g==f&&(d.g="");d.h||(d.h=1);this.od.push(n);this.Db[n]=c}}}}r(Ad,C);Ad.prototype.complete=!0;e=Ad.prototype;e.ug=0;e.od=null;e.ra=null;e.Oc=null;e.Db=null;e.Pe=0;e.Yc=null;
e.Se=0;function Bd(a,b,c,d,f,g){this.g=a;this.e=A([b.x,b.y,b.width,b.height,-c,-d,f,g])}function Ed(a){this.l=a;this.e=null;this.h=1;this.g=""}e=Ed.prototype;e.Oh=function(){return this.l};e.Ci=function(){return this.h};e.Wi=function(a){this.h=a};e.ui=function(){return this.g};e.Ui=function(a){this.g=a};Object.defineProperties(Ed.prototype,{name:{get:Ed.prototype.Oh},speed:{get:Ed.prototype.Ci,set:Ed.prototype.Wi},next:{get:Ed.prototype.ui,set:Ed.prototype.Ui}});
function Cd(a){if(!a.ra&&a.Yc){var b=a.Yc,c=b.width||0,d=b.height||0,f=b.regX||0,g=b.regY||0,b=b.count||0;a.Yc=null;a.ra=[];for(var h=a.Oc,k=h.length,l=0;l<k;++l){var m=h[l],n=m.width/c|0,p=n*(m.height/d|0);0<b&&(p=u(b,p),b-=p);for(var s=0;s<p;++s)a.ra.push(new Bd(m,new G(s%n*c,(s/n|0)*d,c,d),f,g,c,d))}}}e=Ad.prototype;e.wi=function(a){return a?(a=this.Db[a])?a.e.length:0:this.ra?this.ra.length:this.Se};e.hi=function(){return this.od.slice(0)};e.Ke=function(a){return this.Db[a]};
e.Ed=function(a){return this.ra?this.ra[a]:null};e.oi=function(a,b){var c=this.Ed(a);if(c){var d=b||new G(0,0,0,0),f=c.e[5],g=c.e[2],h=c.e[3];d.x=c.e[4];d.y=f;d.width=g;d.height=h;c=d}else c=null;return c};e.handleEvent=function(a){var b=a.type;Ha(a.target,this);"load"==b&&0==--this.Pe&&(Cd(this),this.complete=!0,xa(this,"complete"))};t("createjs.SpriteSheet",Ad,{getNumFrames:Ad.prototype.wi,getAnimations:Ad.prototype.hi,getAnimation:Ad.prototype.Ke,getFrame:Ad.prototype.Ed,getFrameBounds:Ad.prototype.oi});function Fd(a){this.e=a}r(Fd,B);function Gd(a,b){Fc(this);null!=a&&(this.cb=this.spriteSheet=a,this.Je=a.ug,null!=b&&this.qb(b))}r(Gd,L);Gd.prototype.spriteSheet=null;e=Gd.prototype;e.cb=null;e.Je=0;e.Ee="";e.kc=0;e.$f=0;e.Ub=null;function Hd(a,b){if(b!=a.Y){var c=a.cb.Ed(a.Y);if(c){var d=c.e[4],f=c.e[5];M(a,d,f,d+c.e[6],f+c.e[7]);a.k|=4}}}function Id(a){var b=a.ba("animationend"),c=a.Y|0,d;d=a.cb;for(d=d.ra?d.ra.length:d.Se;c>=d;)b&&D(a,new Fd("animationend")),c-=d;a.Y=c}
function Jd(a,b,c){a.oa=b;b=a.Y;if(ga(c)){if(a.Ee!=c){var d=a.cb.Ke(c);a.Ub=d;a.Ee=c;a.Y=d.e[0]}a.kc=0}else a.kc=0,a.Ee="",a.Ub=null,a.Y=c,Id(a);Hd(a,b)}e.Ph=function(){this.oa=!1;this.k=31};e.Qh=function(){this.oa=!0};e.qb=function(a){Jd(this,!1,a);this.k=31};e.$b=function(a){Jd(this,!0,a)};
e.Zf=function(a){var b=1;a&&this.Je&&(b=a*this.Je/1E3);a=this.Y;if(this.Ub){this.kc+=b*this.Ub.h;for(var b=this.ba("animationend"),c=this.Ub,d=this.kc|0,f=c.e.length;d>=f;){var g=c.g;b&&D(this,new Fd("animationend"));if(!g){this.oa=!0;d=f-1;break}c=this.cb.Ke(g);d-=f;f=c.e.length}this.kc=d;this.Y=c.e[d];this.Ub=c}else this.Y=a+b,Id(this);Hd(this,a)};e.V=function(){return Gd.B.V.call(this)?this.cb.complete:!1};e.na=function(){this.cb=this.spriteSheet=null};
e.ga=function(a,b,c,d,f){if(!this.cb.complete)return 0;this.oa||(0<d-this.$f&&this.Zf(d),this.$f=d);return Gd.B.ga.call(this,a,b,c,d,f)};e.va=function(a){var b=this.cb.Ed(this.Y|0);a.Ic(b.g,b.e)};t("createjs.Sprite",Gd,{play:Gd.prototype.Ph,stop:Gd.prototype.Qh,gotoAndPlay:Gd.prototype.qb,gotoAndStop:Gd.prototype.$b,advance:Gd.prototype.Zf});function Kd(a){Fc(this);if(null!=a){var b=this.Ga=ga(a)?Ga(a,a,this,1):a;a=b.width;b=b.height;this.Ob=!!a;this.o||(this.o=new G(0,0,a,b));var c=this.o;this.eb=A([c.x,c.y,c.width,c.height,0,0,a,b,0,0,0,0]);if(c=this.nominalBounds){var d=c.width-a;0<d&&(this.eb[4]=d>>1);c=c.height-b;0<c&&(this.eb[5]=c>>1)}M(this,0,0,a,b)}}r(Kd,L);var Ld=null;e=Kd.prototype;e.Ga=null;e.Ob=!1;e.eb=null;e.Fa=null;e.ne=null;e.Vb=null;e.zf=null;e.pi=function(){return this.Ga};
e.Ri=function(a){this.fa();this.Ga=a;this.Ob=!(!a||!a.width);this.ib(1)};e.Bi=function(){return this.o};e.Vi=function(a){var b=a.width,c=a.height;M(this,0,0,b,c);this.eb||(this.eb=A([0,0,0,0,0,0,0,0]));this.eb.set([a.x,a.y,a.width,a.height,0,0,b,c]);this.o=a};
e.handleEvent=function(a){var b=a.type;a=a.target;Ha(a,this);this.Ob="load"==b;if(this.o&&this.Ob){b=a.width;a=a.height;var c=this.o;c.width=b;c.height=a;c=this.eb;c[0]=0;c[1]=0;c[2]=b;c[3]=a;c[4]=0;c[5]=0;var d=this.nominalBounds;if(d){var f=d.width-b;0<f&&(c[4]=f>>1);d=d.height-a;0<d&&(c[5]=d>>1)}c[6]=b;c[7]=a;M(this,0,0,b,a);this.ib(1)}else this.Ga=null};
e.ib=function(a){if(a&&this.Ob&&(a=this.ke)){var b=a.g;this.Fa||(this.Fa=new xb);a=this.Fa;var c=this.Ga;if(a.g!==b){a.g=b;var d=c.width,f=c.height;a.e||(a.e=new yb(d,f));a.e.e.globalCompositeOperation=Na(9);var g=a.e;g.e.drawImage(b,0,0);for(var b=g.e.getImageData(0,0,d,f),d=b.data,f=d.length,h=0;h<f;h+=4)d[h+3]=d[h];g.e.putImageData(b,0,0);a.e.e.globalCompositeOperation=Na(2);a.e.e.drawImage(c,0,0)}}};e.na=function(){this.fa();this.o=this.Ga=null;this.Ob=!1};
e.fa=function(){var a=this.Fa?zb(this.Fa):this.Ga;a&&this.ne&&(this.ne.rb(a),this.ne=null);if(this.Fa){a=this.Fa;if(a.e){var b=a.e;b.e=null;b.g&&(b.g.width=0,b.g=null);a.e=null}this.Fa=null}};
e.za=function(a,b,c){if(b=L.prototype.za.call(this,a,b,c)){if(this.Vb){c=this.Vb.e[0]-a.e[0];var d=this.Vb.e[1]-a.e[1];if(4>=c*c+d*d)return this.zf;this.Vb.e[0]=a.e[0];this.Vb.e[1]=a.e[1]}else this.Vb=new F(a.e[0],a.e[1]);a=new F(a.e[0],a.e[1]);Db(Mc(this),a);this.o&&(a.e[0]+=this.o.x,a.e[1]+=this.o.y);c=Ld;c||(c=ia(),c.width=1,c.height=1,c=c.getContext("2d"),c.globalCompositeOperation="copy",Ld=c);c.drawImage(this.Ga,-a.e[0],-a.e[1]);c.getImageData(0,0,1,1).data[3]||(b=null);this.zf=b}return b};
e.va=function(a){var b=this.me;b&&a.we(b);a.Ic(this.Fa?zb(this.Fa):this.Ga,this.eb);b&&a.we(null)};e.V=function(){return this.Ob&&Kd.B.V.call(this)};Object.defineProperties(Kd.prototype,{image:{get:Kd.prototype.pi,set:Kd.prototype.Ri},sourceRect:{get:Kd.prototype.Bi,set:Kd.prototype.Vi}});t("createjs.Bitmap",Kd,{});function Md(a){Fc(this);this.e=document.getElementById(a);this.g=Aa().h;a=this.e.style;a.visibility="hidden";a.position="absolute";a[this.g?"webkitTransformOrigin":"transformOrigin"]="0% 0%";M(this,0,0,this.e.clientWidth,this.e.clientHeight)}r(Md,L);Md.prototype.e=null;Md.prototype.g=!1;
Md.prototype.ga=function(a,b,c,d){var f=this.S,g=f.e[6];Md.B.ga.call(this,a,b,c,d,0);b=this.e.style;if(c&2){if(!f.V())return b.visibility="hidden",0;b.visibility="visible";g!=f.e[6]&&(b.opacity=f.e[6])}c&9&&(a.De||(g=a.X,c=g.getBoundingClientRect(),g=window.getComputedStyle(g).zoom,a.De=new F(c.width*g/a.qa,c.height*g/a.pa)),a=a.De,b[this.g?"webkitTransform":"transform"]="matrix("+f.e[0]+","+f.e[1]+","+f.e[2]+","+f.e[3]+","+f.e[4]*a.e[0]+","+f.e[5]*a.e[1]+")");return 0};
t("createjs.DOMElement",Md,{});function Nd(a){Fc(this);this.zc=a;M(this,0,0,a.videoWidth,a.videoHeight)}r(Nd,L);e=Nd.prototype;e.zc=null;e.Jd=!1;e.Id=!1;e.Wc=0;e.be=-1;e.jc=null;e.Vc=null;e.Be=null;e.Hd=null;
e.gi=function(a,b){var c=this.zc;a&&(this.Wc=a,c.currentTime=a);this.Jd=!!b;0>na&&(na=!Ba(4)||navigator.standalone||q.matchMedia("(-webkit-video-playback-inline)").matches?1:0);na?(c.setAttribute("muted",""),c.setAttribute("playsinline",""),c.setAttribute("webkit-playsinline",""),c.loop=this.Jd,this.Jd||this.Id||(this.Id=!0,c.addEventListener("ended",this,!1)),c.play()):(c.load(),this.be=Vc())};e.Ce=function(){var a=this.zc;this.Id&&(this.Id=!1,a.removeEventListener("ended",this,!1));a.pause()};
e.na=function(){this.fa()};e.fa=function(){this.Vc?(this.jc&&this.jc.rb(this.Vc),this.Vc=this.Be=null):this.jc&&this.jc.rb(this.zc);this.Ce();this.zc=null};
e.va=function(a){var b=this.zc;if(!(4>b.readyState)){Pa(this.u)||M(this,0,0,b.videoWidth,b.videoHeight);this.jc||(this.jc=a);var c=b.currentTime;if(0<=this.be){var d=Vc(),c=c+.001*(d-this.be);this.be=d;d=b.duration;c>=d&&(c=this.Jd?c%d:d);b.currentTime=c}if(a.vg())this.Wc!=c&&(this.Wc=c,b.j=1),a.He(b,0,0,Pa(this.u),Qa(this.u));else{d=this.Vc;if(!d){var c=Pa(this.u),f=Qa(this.u),d=ia();d.width=c;d.height=f;this.Vc=d;this.Be=d.getContext("2d");this.Hd=A([0,0,0,0]);this.Hd[2]=c;this.Hd[3]=f;c=-1}this.Wc!=
c&&(this.Wc=c,this.Be.drawImage(b,0,0),d.j=1);a.Xc(d,this.Hd)}}};e.handleEvent=function(a){"ended"==a.type&&(this.Ce(),xa(this,"complete"))};t("createjs.Video",Nd,{play:Nd.prototype.gi,stop:Nd.prototype.Ce});function Od(a){this.e=a}r(Od,B);function Pd(){}r(Pd,C);var Qd=null,Rd=q.requestAnimationFrame||q.webkitRequestAnimationFrame,Sd=q.cancelAnimationFrame||q.webkitCancelAnimationFrame;e=Pd.prototype;e.ye=!1;e.Ne=!1;e.ce=0;e.ed=0;e.pc=50;e.vb=0;e.kd=null;e.jb=0;e.je=!1;e.Rb=null;e.af=null;function Td(a){this.g=[a];this.e=null;this.h=!1}function Ud(a){if(!a.h)return a.g;a.e||(a.e=a.g.slice());return a.e}function Vd(){this.e=0;this.g=new Float64Array(64)}
Vd.prototype.h=function(){var a=u(this.e,64);return 1E3*a/(this.g[this.e-1&63]-this.g[this.e-a&63])};function T(){Qd||(Qd=new Pd);return Qd}function Wd(a){var b=T();b.ce||(b.ce=a,b.vb=a);var c=a-b.vb;if(b.ye)b.ed+=c;else{var c=a-b.ce-b.ed,d=b.Rb;if(d){var f;f=b.Rb;f.h=!0;f=f.g;for(var g=f.length,h=0;h<g;++h)f[h].oc(c);d.h=!1;d.e&&(d.g=d.e,d.e=null)}b.ba("tick")&&(c=T(),c.af||(c.af=new Od("tick")),D(b,c.af))}b.vb=a;b.kd||(b.kd=new Vd);b=b.kd;b.g[b.e&63]=a;++b.e}
function Xd(a){var b=T();b.jb=Rd.call(q,Xd);a-b.vb>=b.pc-1&&Wd(a)}function Yd(){T();Wd(Date.now())}function Zd(a){a.jb&&(a.je?Sd&&Sd.call(q,a.jb):q.clearInterval(a.jb),a.jb=0)}function $d(){var a=T();Zd(a);"timeout"!=ae.timingMode&&Rd?(a.jb=Rd.call(q,Xd),a.je=!0):(a.je=!1,a.jb=q.setInterval(Yd,a.pc))}function qd(a){var b=T();b.Pb();b.Rb=null;a&&Zd(b)}function rd(){var a=T();if(!a.je&&a.jb){var b=Date.now();b-a.vb>=a.pc-1&&Wd(b)}}function be(a){var b=T();b.pc=a;b.Ne&&$d()}
function Vc(){var a=T();return a.vb-a.ce-a.ed}function ce(a){var b=T(),c=b.vb;a&&(c-=b.ed);return c}function de(a,b){var c=T();c.Ne||(c.Ne=!0,$d());if(b.oc){var d=c.Rb;if(d){c=Ud(d);for(d=c.length-1;0<=d;--d)if(c[d]===b)return b;c.push(b)}else c.Rb=new Td(b);return b}return c.Jb(a,b)}function ee(a,b){if(b){var c=T();if(b.oc){if(c=c.Rb)for(var c=Ud(c),d=c.length-1;0<=d;--d)if(c[d]===b){c.splice(d,1);break}}else c.Ib(a,b)}}
var ae=fa("createjs.Ticker",{reset:qd,setInterval:be,getInterval:function(){return T().pc},setFPS:function(a){be(1E3/(60/(60/a|0))|0)},getFPS:function(){return 1E3/T().pc},getMeasuredTickTime:function(){return 0},getMeasuredFPS:function(){var a=T();return a.kd?a.kd.h():0},setPaused:function(a){T().ye=a},getPaused:function(){return T().ye},getTime:ce,getEventTime:ce,getTicks:function(){return 0},addEventListener:de,removeEventListener:ee,removeAllEventListeners:function(a){var b=T(),c=b.Rb;c&&(c.h?
c.e=[]:c.g=[]);b.Pb(a||"")},dispatchEvent:function(a){return T().re(a)},hasEventListener:function(a){return T().ba(a)},timingMode:"synched"});fa("createjs.Touch",{isSupported:function(){return!0},enable:function(a,b,c){a&&pd(a,!0,!c)},disable:function(a){a&&pd(a,!1,!0)}});function fe(a,b,c,d,f){this.Wb=a;this.Te=null==b?"out":b;this.kg=null==d?"down":d;this.wa=!!f;this.Lg(!0);ge(this,this.Te)}r(fe,ja);e=fe.prototype;e.Wb=null;e.Te="out";e.kg="down";e.wa=!1;e.rg=!1;function ge(a,b){a.wa?a.Wb.qb&&a.Wb.qb(b):a.Wb.$b&&a.Wb.$b(b)}e.Lg=function(a){a=!!a;if(this.rg!=a){this.rg=a;var b=this.Wb;a?(b.Jb("mousedown",this),b.Jb("pressup",this)):(b.Ib("mousedown",this),b.Ib("pressup",this))}};
e.handleEvent=function(a){a=a.type;var b="";"mousedown"==a?b=this.kg:"pressup"==a&&(b=this.Te);ge(this,b)};t("createjs.ButtonHelper",fe,{setEnabled:fe.prototype.Lg});function he(){}r(he,C);function ie(a,b){var c=ia();c.width=a;c.height=b;Ma.call(this,c,a,b);this.D=this.C=0;this.e=c.getContext("2d")}r(ie,Ma);e=ie.prototype;e.qd=function(a,b,c,d){var f=this.e;f.save();f.beginPath();f.rect(a,b,c,d);f.clip();this.C=a;this.D=b};e.Ud=function(){this.e.restore()};e.Cd=function(a){this.e.setTransform(a[0],a[1],a[2],a[3],a[4]+this.C,a[5]+this.D);this.e.globalAlpha=a[6];this.e.globalCompositeOperation=Na(a[7])};
e.Ic=function(a,b){this.e.drawImage(a,b[0],b[1],b[2],b[3],b[4],b[5],b[6],b[7])};e.nd=function(a){Xa(a,this);a.va(this)};he.prototype.e=null;he.prototype.xa=1;he.prototype.g=function(a,b,c){this.e=a;this.xa=c||1};
he.prototype.h=function(){var a=[],b=[],c=this.e;c.td(this.xa);c.ud(this.xa);for(var d=new N,f=-1,g=c.zd;64<=g;){var h=2048,k=2048,l=new ie(h,k),m=l.X;a.push(m);for(var n=0;n<k;n+=256)for(var p=0;p<h;p+=256){l.qd(p,n,256,256);var s=c,v=l,w=d,y=++f;s.Sb(y);s.ga(v,w,0,y,1);l.Ud();v=new Bd(m,new G(p,n,256,256),0,0,256,256);b.push(v)}l.Jc(0);g-=64}if(g){s=g+8-1>>3;h=2048;k=s<<8;l=new ie(h,k);m=l.X;a.push(m);k-=256;for(n=0;n<k;n+=256)for(p=0;p<h;p+=256){l.qd(p,n,256,256);var v=c,w=l,y=d,E=++f;v.Sb(E);
v.ga(w,y,0,E,1);l.Ud();v=new Bd(m,new G(p,n,256,256),0,0,256,256);b.push(v)}g-=8*(s-1);h=256*g;for(p=0;p<h;p+=256)l.qd(p,k,256,256),s=c,v=l,w=d,y=++f,s.Sb(y),s.ga(v,w,0,y,1),l.Ud(),v=new Bd(m,new G(p,n,256,256),0,0,256,256),b.push(v);l.Jc(0)}d=new Ad(null);d.Oc=a;d.ra=b;a=[];b={};c=c.Ad();if(f=c.length)for(l=0;l<f;++l){h=c[l];m=h.label;p=l==f-1?g:c[l+1].position;n=[];for(h=h.position;h<p;++h)n.push(h);p=new Ed(m);p.e=n;a.push(m);b[m]=p}d.od=a;d.Db=b;return d};
t("createjs.SpriteSheetBuilder",he,{addFrame:da,addAnimation:da,addMovieClip:he.prototype.g,build:he.prototype.h,buildAsync:da,stopAsync:da});function je(){this.e={}}r(je,C);var ke=null;function R(){ke||(ke=new je);return ke}je.prototype.e=null;function le(){}t("createjs.HTMLAudioPlugin",le,{},{enableIOS:!0});function me(){}me.context={currentTime:-1};var ud=!1,td=null,sd=null,ne=null;function oe(a){q.removeEventListener(a.type,oe,!1);a=td;if(!a.currentTime){a.resume&&a.resume();if(!Ba(4)){a=R();for(var b in a.e){var c=a.e[b];c&&c.Kg()}}pe()}}
function qe(){if(!td.currentTime){var a;a=Ba(4)&&9!=Aa().l?"touchstart":"touchend";q.addEventListener(a,oe,!1)}}function pe(){var a=td;a.state||(a=a.createBufferSource(),a.buffer=ne,a.start?a.start(0):a.noteOn(0),setTimeout(qe,100))}function re(){if(!ud&&(ud=!0,ca)){var a=new ca;td=a;ne=a.createBuffer(1,1,22500);a.state?"running"!=a.state&&qe():pe()}return td}t("createjs.WebAudioPlugin",me,{},{playEmptySound:function(){re()}});function se(a){this.O=a}r(se,C);se.prototype.playState=5;e=se.prototype;
e.O=null;e.Mc=0;e.tb=0;e.sb=0;e.hb=1;e.wa=function(a,b,c,d,f){null!=d&&(this.Mc=d);0<=c&&(this.tb=c);null!=f&&(this.hb=f);this.playState=2};e.ha=function(){this.playState=4};e.Nc=function(){};e.Dd=function(){};e.We=function(){};e.Kg=function(){};e.Ag=function(){return!0};se.prototype.play=da;se.prototype.stop=da;se.prototype.setMute=da;se.prototype.setVolume=da;function U(a){this.O=a}r(U,se);e=U.prototype;e.Kc=0;e.Lc=!0;e.he=0;function te(a,b,c,d){a.Kc&d||(b.addEventListener(c,a,!1),a.Kc|=d)}
function ue(a,b,c,d){b.removeEventListener(c,a,!1);a.Kc&=~d}e.Nh=function(){this.he=0;this.ha();xa(this,"complete")};e.L=function(){if(this.Lc){var a=this.O.K;!this.Mc&&this.sb&&(this.tb&&(a.currentTime=this.tb),this.he&&clearTimeout(this.he),this.he=setTimeout(this.Nh.bind(this),this.sb));var b=this.hb;1!=b&&(a.volume=b);te(this,a,"ended",4);a.play();(this.Lc=a.paused)&&this.Mc&&te(this,window,"touchstart",8)}};
e.wa=function(a,b,c,d,f,g){this.Lc&&(U.B.wa.call(this,a,b,c,d,f,g),a=this.O.K,a.parentNode||document.body.appendChild(a),4!=a.readyState?(te(this,a,"canplay",1),a.g="auto",a.load()):this.L())};e.ha=function(){var a=this.O.K;a.pause();var b=a.parentNode;b&&b.removeChild(a);ue(this,a,"canplay",1);ue(this,a,"ended",4);ue(this,window,"touchstart",8);this.Lc=!0;U.B.ha.call(this)};e.Nc=function(a){this.O&&(this.O.K.e=a)};e.Dd=function(a){this.O&&this.hb!=a&&(this.hb=a,this.O.K.volume=a)};
e.We=function(a,b,c){this.tb=.001*b;this.sb=c};e.handleEvent=function(a){var b=a.type;a=a.target;"canplay"==b?(ue(this,a,b,1),this.L()):"ended"==b?this.Mc?a.play():this.ha():"touchstart"==b&&(ue(this,window,b,8),this.L())};U.prototype.play=U.prototype.wa;U.prototype.stop=U.prototype.ha;U.prototype.setMute=U.prototype.Nc;U.prototype.setVolume=U.prototype.Dd;function V(a){this.O=a}r(V,se);
function ve(){var a=document.createElement("iframe");a.id="cjs-iframe";var b=a.style;b.zIndex=-1;b.position="absolute";b.border="0px";b.top="0px";b.left="0px";b.width="1px";b.height="1px";q.addEventListener("message",this,!1);a.src='data:text/html,<html style="-webkit-user-select:none;"><head><script type="text/javascript">var e=window,f=e.webkitAudioContext||e.AudioContext,g=null,h=null;function k(){this.e={}}function l(a,b){this.h=a;this.g=b}l.prototype.e=null;l.prototype.f=function(a){this.e=a;for(var b=[],d=0;d<a.numberOfChannels;++d)b.push(a.getChannelData(d));this.g.postMessage({a:6,b:this.h,c:a.sampleRate,d:b},"*")};k.prototype.handleEvent=function(a){if("message"==a.type){var b=a.data,d=b.b;if(0==b.a){var c=this.e[d];c?(c.g=a.source,c.f(c.e)):(c=new l(d,a.source),this.e[d]=c,a=c.f.bind(c),g.decodeAudioData(b.c,a,a))}}};e.onload=function(){g=new f;h=new k;e.addEventListener("message",h,!1);e.parent.postMessage({a:4},"*")};\x3c/script></head><body></body></html>';
document.body.appendChild(a);this.h=a;this.e=[];this.g={}}ve.prototype.h=null;ve.prototype.e=null;ve.prototype.g=null;ve.prototype.handleEvent=function(a){var b=a.data;a=b.a;if(4==a){if(this.e){if(a=this.h.contentWindow)for(var c=0;c<this.e.length;++c)a.postMessage(this.e[c],"*");this.e=null}}else if(6==a&&(a=this.g[b.b])){var c=b.c,b=b.d,d=ne;if(1<=b.length)for(d=b[0].length,d=re().createBuffer(b.length,d,c),c=0;c<b.length;++c)d.getChannelData(c).set(b[c]);a.zg(d)}};var we=null;e=V.prototype;
e.o=null;e.Fb=null;e.ad=null;e.pd=0;e.Mh=function(){this.ha();xa(this,"complete")};function xe(a,b){var c=re(),d=c.createGain?c.createGain():c.createGainNode();d.connect(c.destination);d.gain.value=a.hb;a.Fb=d;c=c.createBufferSource();c.connect(d);c.buffer=b;a.Mc?(c.loop=!0,c.start?c.start(0):c.noteOn(0)):(c.onended=a.Mh.bind(a),c.start?c.start(0,a.tb,a.sb):c.noteGrainOn(0,a.tb,a.sb));a.o=c}
e.zg=function(a){this.sb=a.duration;this.O.K=a;if(this.ad){var b=this.ad,c=b.Gb;a?(c.K=a,b.pb||ye(b.Da,b)):ze(b);this.ad=null}this.pd&&(xe(this,a),this.pd=0)};e.wa=function(a,b,c,d,f,g){V.B.wa.call(this,a,b,c,d,f,g);this.O.K?(this.o&&this.ha(),xe(this,this.O.K)):this.pd=1};
e.ha=function(){V.B.ha.call(this);this.pd=0;var a=this.o;a&&(3!=(a.playbackState||0)&&(a.stop?a.stop(0):a.noteOff(0)),a.disconnect(0),a.onended=null,Ba(4)&&(ne||(ne=re().createBuffer(1,1,22500)),this.o.buffer=ne),this.o=null,this.Fb.disconnect(0),this.Fb=null)};e.Nc=function(a){this.Fb&&(this.Fb.gain.value=a?0:this.hb)};e.Dd=function(a){this.hb!=a&&(this.hb=a,this.Fb&&(this.Fb.gain.value=a))};e.We=function(a,b,c){this.tb=.001*b;this.sb=.001*c};
e.Kg=function(){this.o&&(this.ha(),xe(this,this.O.K),this.playState=2)};e.Ag=function(a,b){if(b){var c=re();if(Ba(3)&&2==Aa().e){we||(we=new ve);var d=we,f=this.O.id,c=!this.O.Ze;d.g[f]?c=!0:(d.g[f]=this,f={a:0,b:f,c:b},d.e?d.e.push(f):(d=d.h.contentWindow)&&d.postMessage(f,"*"));c||(this.ad=a);return c}d=V.prototype.zg.bind(this);c.decodeAudioData(b,d,d);if(this.O.Ze)return this.ad=a,!1}return!0};V.prototype.play=V.prototype.wa;V.prototype.stop=V.prototype.ha;V.prototype.setMute=V.prototype.Nc;
V.prototype.setVolume=V.prototype.Dd;function Ae(){}function Be(a){if(re())return new V(a);Ba(4);return new U(a)}function Ce(a,b){var c=a.e[b];if(!c)return!1;c.ha();var c=c.O,d=c.o;a.e[d]=null;c.id!=d&&(a.e[c.id]=null);return!0}je.prototype.wa=function(a,b,c,d,f,g,h){(a=this.e[a])&&a.wa(0,c,d,f,g,h)};je.prototype.ha=function(){};
function De(a,b,c){b=b||a;a=R();b=a.e[b];c=c.audioSprite;if(b&&c)for(var d=0;d<c.length;++d){var f=c[d],g=f.id,h=f.startTime,f=f.duration,k=Be(b.O);k.We(g,h,f);a.e[g]=k}}
fa("createjs.Sound",{INTERRUPT_ANY:0,INTERRUPT_EARLY:1,INTERRUPT_LATE:2,INTERRUPT_NONE:3,PLAY_SUCCEEDED:2,PLAY_FINISHED:4,PLAY_FAILED:5,activePlugin:ca?new me:new le,initializeDefaultPlugins:function(){return!0},isReady:function(){return!0},createInstance:function(a){return R().e[a]},registerSound:De,registerSounds:function(a){for(var b=0;b<a.length;++b){var c=a[b];De(c.src,"",c.data)}},removeSound:function(a){var b=R();return"object"==typeof a?Ce(b,a.src):Ce(b,a)},play:function(a,b,c,d,f,g,h){if(null!=
b&&"object"==typeof b){var k=b;b=k.interrupt;c=k.delay;d=k.offset;f=k.loop;g=k.volume;h=k.pan}k=3;ga(b)&&(k={any:0,early:1,late:2,none:3}[b]||3);b=c||0;d=d||0;f=f||0;g=null==g?1:g;h=h||0;R().wa(a,k,b,d,f,g,h)},addEventListener:function(a,b){return R().Jb(a,b)},removeEventListener:function(a,b){R().Ib(a,b)},removeAllEventListeners:function(a){R().Pb(a||"")},dispatchEvent:function(a){return R().re(a)},hasEventListener:function(a){return R().ba(a)},setMute:function(a){var b=R(),c;for(c in b.e){var d=
b.e[c];d&&d.Nc(a)}return!0},setVolume:function(){R()}});r(function(a){this.e=a},B);function Ee(a){this.e=a}r(Ee,B);function Fe(a,b,c,d){this.e=a;this.item=d}r(Fe,B);function Ge(a,b,c,d){Fe.call(this,a,0,0,d)}r(Ge,Fe);r(function(a,b,c,d,f,g,h){Fe.call(this,a,0,0,d);this.loaded=f;this.total=g;this.progress=h},Fe);function He(a,b,c,d,f,g){Fe.call(this,a,0,0,d);this.result=f;this.rawResult=g}r(He,Fe);function Ie(a,b){this.Da=a;this.Gb=b}var Je=" image sound json css javascript manifest text video html".split(" "),Ke=[1,1,1,1,1,1,2,2,2,2,2,3,4,5];function Le(){}e=Le.prototype;e.id="";e.ae="";e.$d=null;e.K=null;e.o="";e.jd=!1;e.v=0;e.Gc=null;e.Ie=-1;e.ve="";e.Da=null;e.Eb=0;e.Ze=!1;function Me(a){return 1==a.v||2==a.v||8==a.v}e=Ie.prototype;e.Da=null;e.Gb=null;e.Wf=!1;e.pb=!1;e.bb=null;
function Ne(a){if(a.bb){var b=a.bb;b.removeEventListener("error",a,!1);b.removeEventListener("load",a,!1);a.bb=null}}
function Oe(a,b,c){a.Wf=!0;if(1==b.v)return c=Ga(b.ve,c,a,b.Eb),b.K=c,c.complete;if(2==b.v){if(!b.jd){if(c=b.Da){var d=b.$d;b.$d=null;return c.Ag(a,d)}return!0}a=document.createElement("audio");a.autoplay=!1;a.src=c;b.K=a;return!0}if(5==b.v)return a=document.createElement("script"),a.type="text/javascript",a.text=c,b.K=a,!0;if(4==b.v)return a=document.createElement("style"),a.type="text/css",a.styleSheet?a.styleSheet.cssText=c:a.appendChild(document.createTextNode(c)),document.head.appendChild(a),
b.K=a,!0;if(3==b.v||6==b.v)return b.K=JSON.parse(c),!0;if(8==b.v)return a=document.createElement("video"),a.crossOrigin="anonymous",a.src=c,b.K=a,!0;b.K=c;return!0}function ze(a){Ne(a);if(!a.pb){var b=a.Da;++b.Zb;Pe(b);Qe(b,a.Gb.Gc);Re(b,a);a=a.Gb;if(5==a.v)for(var c=b.Ka.length,d=0;d<c;++d)if(b.Ka[d]===a){b.Ka.splice(d,1);break}Se(b)}}
e.handleEvent=function(a){var b=a.target;b instanceof HTMLImageElement&&Ha(b,this);if("load"==a.type)if(this.Wf)this.pb||ye(this.Da,this);else if(200!=this.bb.status)ze(this);else{a=this.Gb;b=this.bb.response||this.bb.responseText;if(Me(a))if(a.$d=b,a.jd){var c=this.bb.getResponseHeader("Content-Type");if(ba){var d=new ba;d.append(b);b=d.getBlob(c)}else b=new Blob([b],{type:c});b=aa.createObjectURL(b)}else b="";else a.ae=b;Ne(this);Oe(this,a,b)&&!this.pb&&(ye(this.Da,this),this.pb=!0);a.$d=null}else ze(this)};function W(a,b){this.nf=b||"";this.tc=[];this.Ia=[];this.Pa={};this.Ka=[];this.Da=new Ae}r(W,C);e=W.prototype;e.nf="";e.tc=null;e.Ia=null;e.Pa=null;e.Ka=null;e.Da=null;e.Xe=!1;e.xd=!0;e.uh=0;e.yf=1;e.hd=0;e.Zb=0;function Qe(a,b){a.ba("error")&&D(a,new Ge("error",0,0,b))}function Te(a,b){R().e[b.id]&&(a.Pa[b.o]=null,a.Pa[b.id]=null);a.ba("fileload")&&D(a,new He("fileload",0,0,b.Gc,b.K,b.ae))}
function Pe(a){var b=1/a.hd,c=a.Zb*b;if(a.hd>a.Zb){for(var d=0,f=a.Ia.length,g=0;g<f;++g)d+=0;c+=d*b}a.uh=c;a.ba("progress")&&D(a,new Ee("progress"))}function Re(a,b){for(var c=a.Ia.length,d=0;d<c;++d)if(a.Ia[d]==b){a.Ia.splice(d,1);break}}
function Ue(a,b){var c=new Le,d=a.nf,f=b.src;f&&(c.o=f);if(f=b.type)for(var g=1;g<Je.length;++g)if(Je[g]==f){c.v=g;break}f=b.id;null!=f&&(c.id=f+"");c.Eb=b.format||0;c.Ze=!!b.sync;c.Gc=b;f=new Ca(c.o);f.e?(g=f.e.lastIndexOf("."),g=0>g?"":f.e.substring(g+1).toLowerCase()):g="";c.Ie={jpeg:0,jpg:1,gif:2,png:3,webp:4,bmp:5,ogg:6,mp3:7,mp4:8,m4a:9,wav:10,json:11,css:12,js:13}[g]||-1;!c.v&&0<=c.Ie&&(c.v=Ke[c.Ie],c.Gc.type=Je[c.v]);c.ve=!f.g&&f.e&&47!=f.e.charCodeAt(0)?d+c.o:c.o;1==c.v||5==c.v||4==c.v||
8==c.v?c.jd=!0:2==c.v&&(c.jd=!ca);c.id||(c.id=c.o);a.Pa[c.o]=c;c.o!=c.id&&(a.Pa[c.id]=c);2==c.v&&(d=R(),f=c.o,g=d.e[f],g||(g=Be(c),d.e[f]=g,c.id!=f&&(d.e[c.id]=g)),c.Da=g);a.tc.push(new Ie(a,c));++a.hd;Pe(a);5==c.v&&a.Ka.push(c)}
function Se(a){if(!a.xd)if(a.Xe||(a.ba("loadstart")&&xa(a,"loadstart"),a.Xe=!0),a.loaded=a.hd==a.Zb,a.loaded)xa(a,"complete");else for(var b=0;b<a.yf-a.Ia.length&&a.tc.length;++b){var c=a.tc.shift();a.Ia.push(c);var d=c,c=d.Gb,f=c.ve,g=void 0;1==c.v||2==c.v&&c.jd?g=null:(g=new XMLHttpRequest,g=Me(c)&&null==g.responseType?null:g);g?(g.open("GET",f,!0),g.addEventListener("error",d,!1),g.addEventListener("load",d,!1),!Me(c)&&g.overrideMimeType("text/plain; charset=utf-8"),Me(c)&&(g.responseType="arraybuffer"),
g.send(),d.bb=g):Oe(d,c,f)&&!d.pb&&(ye(d.Da,d),d.pb=!0)}}e.Xi=function(a){return a};e.Ii=function(){};e.Ai=function(a,b){var c=this.Pa[a];return c?b&&c.ae?c.ae:c.K:null};e.Ni=function(){this.ue();this.Pa={};W.call(this)};e.vh=function(){};e.Ti=function(a){this.yf=a;!this.xd&&0<this.tc.length&&Se(this)};e.Ji=function(a,b){a?(Ue(this,ga(a)?{src:a}:a),this.yd(null==b?!1:!b)):Qe(this,{})};e.Ki=function(a,b){if(a.length){for(var c=0;c<a.length;++c)Ue(this,a[c]);this.yd(null==b?!1:!b)}else Qe(this,{})};
e.sh=function(a){return this.Pa[a].Gc};e.yd=function(a){(this.xd=a)||Se(this)};e.th=function(){this.yd(!1)};e.ue=function(){for(var a=0;a<this.Ia.length;++a){var b=this.Ia[a];Ne(b);b.bb.abort()}this.Ia=[];this.Ka=[];this.Xe=!1};e.wh=function(){this.ue();this.tc=[];this.Pa={};this.Zb=this.hd=0};
function ye(a,b){Re(a,b);var c=b.Gb;if(5==c.v){for(var d=a.Ka.length,c=c=0;c<d&&a.Ka[c].K;++c);if(0<c){for(d=0;d<c;++d){var f=a.Ka[d];document.body.appendChild(f.K);Te(a,f)}a.Ka.splice(0,c)}}else Te(a,c);++a.Zb;Pe(a);Se(a)}
t("createjs.LoadQueue",W,{setUseXHR:W.prototype.Xi,installPlugin:W.prototype.Ii,getResult:W.prototype.Ai,removeAll:W.prototype.Ni,remove:W.prototype.vh,setMaxConnections:W.prototype.Ti,loadFile:W.prototype.Ji,loadManifest:W.prototype.Ki,getItem:W.prototype.sh,setPaused:W.prototype.yd,load:W.prototype.th,close:W.prototype.ue,reset:W.prototype.wh},{BINARY:"binary",CSS:"css",IMAGE:"image",JAVASCRIPT:"javascript",JSON:"json",JSONP:"jsonp",MANIFEST:"manifest",SOUND:"sound",SVG:"svg",TEXT:"text",XML:"xml"});function Ve(){}Ve.prototype.R=function(a){return a};function We(a){this.e=a}We.prototype.R=function(a){return 0>this.e?a*(a*-this.e+1+this.e):a*((2-a)*this.e+(1-this.e))};function Xe(){}Xe.prototype.R=function(a){return a*(2-a)};function Ye(){}Ye.prototype.R=function(a){return a*a};function Ze(){}Ze.prototype.R=function(a){a=1-a;return 1-a*a};function $e(){}$e.prototype.R=function(a){a*=2;if(1>a)return.5*a*a;a=2-a;return 1-.5*a*a};function af(){}af.prototype.R=function(a){return a*a*a};
function bf(){}bf.prototype.R=function(a){a=1-a;return 1-a*a*a};function cf(){}cf.prototype.R=function(a){a*=2;if(1>a)return.5*a*a*a;a=2-a;return 1-.5*a*a*a};var df=new Ve,ef=new Xe,ff=new Ye;fa("createjs.Ease",{linear:df,none:df,get:function(a){return 0==a?df:1<=a?ef:-.99>=a?ff:new We(a)},quadIn:ff,quadOut:new Ze,quadInOut:new $e,cubicIn:new af,cubicOut:new bf,cubicInOut:new cf});function X(a){this.M=a}r(X,C);e=X.prototype;e.wb=0;e.Tc=!1;e.la=0;e.Ta=0;e.fd=-1;e.Uc=!1;e.$=0;e.Tb=0;e.yb=!1;e.xc=!1;e.M=null;e.kb=null;e.La=null;e.Z=null;e.ma=null;e.ca=null;e.Qb=null;e.xb=0;e.Nb=null;e.P=null;e.Sa=0;e.Vg=!1;e.Zd=!1;e.I=0;function gf(a,b,c,d){this.e=a;this.h=b;this.l=c[0];this.m=c[1];this.J=c[2];this.g=d}function hf(a){a.h.call(a.g,a.l,a.m,a.J)}function jf(a,b,c){this.e=a;this.g=b;this.h=c}
function kf(a,b,c,d){var f=a.e,g=a.h;d.L=b;d.fc=b+f;d.ze=f;d.xa=1/f;d.ec=g;a.g&&(b=Bc(d,a.g))&&c.ff(b);return a.e}function lf(a,b,c,d){var f=a.e;d.L=b;d.Sc=b+f;for(var g=0;g<d.uc;++g){var h=d.ic[g],k=b,l=f;h.L=k;h.fc=k+l;h.ze=l;h.xa=1/l;h.ec=null}if(a.g){b=d.ic.slice(0);d=a.g.state;f=d.length;for(g=0;g<f;++g)l=d[g],h=c[l.t.$e],k=b[h],Ac(k,0),(l=l.p)&&Bc(k,l),b[h]=null;if(f<b.length)for(f=b.length,g=0;g<f;++g)(k=b[g])&&Ac(k,1)}return a.e}
function mf(a,b,c,d){if(a.La){var f=a.La;a.La=null;if(b){var g=b[c];if(g){a.Z=g.Z;a.ca=g.ca;a.ma=g.ma;a.xb=g.xb;return}b[c]=a}if(a.M){var h=new vc;a.Z?zc(a.Z[a.Z.length-1],h):(d&&(a.ma=[]),a.Z=[],a.M.mc(h));if(b=kf(f[0],a.I,a.M,h)){if(d){var k=a.I;c=a.I+b;for(g=a.Z.length;k<c;++k)a.ma[k]=g}a.I+=b;a.Z.push(h)}for(var l=f.length,m=1;m<l;++m){var n=new vc;zc(h,n);if(b=kf(f[m],a.I,a.M,n)){if(d)for(k=a.I,c=a.I+b,g=a.Z.length;k<c;++k)a.ma[k]=g;a.I+=b;a.Z.push(n)}h=n}d&&(a.ma[a.I]=a.Z.length-1);a.xb|=h.ka}else{a.P||
(a.P=[],a.Qb={});h=a.P.length;n=new Dc(h);if(a.ca)Ec(a.ca[a.ca.length-1],n);else for(d&&(a.ma=[]),a.ca=[],m=0;m<h;++m)a.P[m].mc(n.get(m));if(b=lf(f[0],a.I,a.Qb,n)){if(d)for(k=a.I,c=a.I+b,g=a.ca.length;k<c;++k)a.ma[k]=g;a.I+=b;a.ca.push(n)}l=f.length;for(m=1;m<l;++m){var p=new Dc(h);Ec(n,p);if(b=lf(f[m],a.I,a.Qb,p)){if(d)for(k=a.I,c=a.I+b,g=a.ca.length;k<c;++k)a.ma[k]=g;a.I+=b;a.ca.push(p)}n=p}}}}function nf(a,b){a.Zd=!0;a.Sa=Vc();b?b.Ig(a):de("tick",a)}
function of(a,b,c){mf(a,null,0,a.xc);b>=a.la&&(a.wb&&a.la?(b%=a.la,c=!0,a.$=0):(b=a.la,a.Tc=!0));if(a.M){if(a.Z){var d=a.Z.length-1;if(0<=d){if(a.ma){var f=a.ma[b],g=a.Z[f];if(g&&(c=c||b==g.L||b==g.fc,!g.dd||f!=a.$||c)){var h=g.R(b,c);h&16384&&(a.wb=g.e[14]);a.M.ya(g,c?a.xb:h,a.Nb)}a.$=f;return b}for(f=a.$;f<d;++f)if(g=a.Z[f],b<g.fc){c=c||b==g.L||b==g.fc;if(!g.dd||f!=a.$||c)h=g.R(b,c),h&16384&&(a.wb=g.e[14]),a.M.ya(g,c?a.xb:h,a.Nb);a.$=f;return b}g=a.Z[d];c=c||b==g.L||b==g.fc;if(!g.dd||d!=a.$||c)h=
g.R(b,c),h&16384&&(a.wb=g.e[14]),a.M.ya(g,c?a.xb:h,a.Nb);a.$=d}}}else if(a.ca&&(d=a.ca.length-1,0<=d)){if(a.ma){f=a.ma[b];if(g=a.ca[f])if(c=c||b==g.L||b==g.Sc,f!=a.$||c)for(var k=a.P.length,l=0;l<k;++l){var m=g.get(l),h=Cc(m,b,c);a.P[l].ya(m,h,a.Nb)}a.$=f;return b}for(f=a.$;f<d;++f)if(g=a.ca[f],b<g.Sc){c=c||b==g.L||b==g.Sc;if(f!=a.$||c)for(k=a.P.length,l=0;l<k;++l)m=g.get(l),h=Cc(m,b,c),a.P[l].ya(m,h,a.Nb);a.$=f;return b}g=a.ca[d];c=c||b==g.L||b==g.Sc;if(d!=a.$||c)for(k=a.P.length,l=0;l<k;++l)m=g.get(l),
h=Cc(m,b,c),a.P[l].ya(m,h,a.Nb);a.$=d}return b}e.Di=function(){return this.M};e.ci=function(){return this.la};e.di=function(){return this.Ta};e.Ae=function(a){a=!!a;var b=Vc();a?Qc(this,b):pf(this,b);return this};e.$g=function(a){if(null==a||a!==a||0>=a)return this;this.La||(this.La=[]);this.La.push(new jf(a,null,null));this.la+=a;return this};
e.Xg=function(a,b,c){if(null==b||b!==b||0>b)b=0;this.La||(this.La=[]);c=c||null;c===df&&(c=null);this.La.push(new jf(b,a,c));if(!this.M)for(this.P||(this.P=[],this.Qb={}),a=a.state,c=0;c<a.length;++c){var d=a[c].t,f=d.$e;if(null==this.Qb[f]){var g=this.P.length;this.P[g]=d;this.Qb[f]=g}}this.la+=b;return this};e.call=function(a,b,c){this.kb||(this.kb=[]);this.kb.push(new gf(this.la,a,b||[],c||this.M));return this};e.set=function(){return this};
e.fi=function(a){a||(a=this);return this.call(a.Ae,[!1],a)};e.ei=function(a){a||(a=this);return this.call(a.Ae,[!0],a)};
function Tc(a,b,c,d){if(0<=d&&(a.Tb=0,a.Ta!=d)){var f=c&4;a.Gd(d,f);if(f)return a.Ta}if((b==a.Sa||a.yb||a.Vg||a.Tc)&&!a.Uc)return a.Sa=b,a.Ta;f=a.Ta;d=of(a,f,a.Uc);a.Uc=!1;a.Ta=-1;if(2!=(c&3)&&(c=a.fd,a.kb)){for(var g=a.kb.length,h=a.Tb;h<g;++h){var k=a.kb[h];if(f<k.e)break;c<k.e&&k.e<=f&&(a.Tb=h,hf(k))}if(a.wb&&f>a.la&&(a.Tb=0,!a.xc))for(f%=a.la,h=0;h<g;++h){k=a.kb[h];if(f<k.e)break;0<=k.e&&k.e<=f&&(a.Tb=h,hf(k))}}0>a.Ta&&(a.fd=d,a.Ta=d+(a.xc?1:b-a.Sa));a.Sa=b;return a.fd}
function pf(a,b){a.yb&&(a.Zd||nf(a,a.M),a.Sa=b,a.yb=!1)}function Qc(a,b){a.yb||(a.Sa=b,a.yb=!0)}
function qf(a,b,c,d,f){if(!b||a.M!==b){var g=a.M;a.Zd=!1;a.Sa=0;if(g){if(g.T)for(var g=Hc(g.T),h=g.length-1;0<=h;--h)if(g[h]===a){g.splice(h,1);break}}else ee("tick",a);a.M?c.unshift(a.M):a.P?c.unshift.apply(c,a.P):(a.P=[],a.Qb={});if(b)if(nf(a,b),a.Nb=b,a.M)c=a.M,2==c.i[11]&&Wc(b,a.M,!0);else for(g=0;g<a.P.length;++g)c=a.P[g],2==c.i[11]&&Wc(b,c,!0);mf(a,d,f,!0);a.Zd=!0}a.xc=!0;a.Sa=Vc()-1;return a.la}
e.Gd=function(a,b){this.Tb=this.$=0;this.Tc=!1;if(b){if(!this.xc)return;this.fd!=a&&of(this,a,!0)}this.fd=a-1;this.Ta=a;this.Uc=!0};function rf(a,b,c){a.wb=b;if(a.Vg=c)a.Uc=!0}e.oc=function(a){Tc(this,a,0,-1);this.Tc&&ee("tick",this)};Object.defineProperties(X.prototype,{target:{get:X.prototype.Di},duration:{get:X.prototype.ci},position:{get:X.prototype.di}});
t("createjs.Tween",X,{setPaused:X.prototype.Ae,wait:X.prototype.$g,to:X.prototype.Xg,call:X.prototype.call,set:X.prototype.set,play:X.prototype.fi,pause:X.prototype.ei,setPosition:X.prototype.Gd,w:X.prototype.$g,t:X.prototype.Xg,c:X.prototype.call,s:X.prototype.set},{get:function(a,b,c,d){a&&!a.Ig&&(a=null);d&&a&&Pc(a);c=new X(a);b&&(c.wb=b.loop|0,c.yb=!!b.paused,c.xc=!!b.useTicks);c.yb||nf(c,a);return c},removeTweens:function(a){Pc(a)},removeAllTweens:function(){},hasActiveTweens:function(a){return a?
!!a.T&&!!a.T.h.length:!0},installPlugin:function(){}});fa("createjs.MotionGuidePlugin",{install:function(){}});function Y(a,b,c){this.Ha=[];this.eg=b;c&&(this.fg=c.loop|0,this.Rc=!!c.paused);sf(this,a,a.length);this.Rc||(this.Rc=!0,this.gg(!1))}r(Y,C);Y.prototype.duration=0;e=Y.prototype;e.Ha=null;e.eg=null;e.fg=0;e.Rc=!1;function sf(a,b,c){for(var d=[],f=0;f<c;++f){for(var g=b[f],h=0;h<a.Ha.length;++h)if(g===a.Ha[h]){g=null;break}g&&(h=qf(g,null,d,null,0),a.duration<h&&(a.duration=h),rf(g,a.fg,!1),a.Ha.push(g))}}e.Wh=function(a){var b=arguments;sf(this,b,b.length);return b[0]};e.ai=function(){return!1};
e.Vh=function(a,b){this.eg[a]=b};e.bi=function(){};e.Yh=function(){return null};e.Xh=function(){return""};e.gg=function(a){var b=!!a;if(this.Rc!=b)if(this.Rc=b,a=Vc(),b){for(b=0;b<this.Ha.length;++b)Qc(this.Ha[b],a);ee("tick",this)}else{for(b=0;b<this.Ha.length;++b)pf(this.Ha[b],a);de("tick",this)}};e.Zh=function(){};e.$h=function(){};e.oc=function(a){for(var b=0,c=0;c<this.Ha.length;++c){var d=this.Ha[c];Tc(d,a,0,-1);b|=d.Tc?0:1}b||ee("tick",this)};
t("createjs.Timeline",Y,{addTween:Y.prototype.Wh,removeTween:Y.prototype.ai,addLabel:Y.prototype.Vh,setLabels:Y.prototype.bi,getLabels:Y.prototype.Yh,getCurrentLabel:Y.prototype.Xh,setPaused:Y.prototype.gg,gotoAndPlay:Y.prototype.Zh,gotoAndStop:Y.prototype.$h});function Z(a,b,c,d){N.call(this);this.timeline=new $(this);this.ac=d||{};this.Bd=[];this.i[10]=b|0;this.i[14]=null==c?1:c|0;this.i[11]="single"==a?1:"synched"==a?2:0}r(Z,N);function tf(a,b){this.label=a;this.position=b}function uf(a,b){return a.position-b.position}function $(a){this.e=a}e=$.prototype;e.Ah=function(){return this.e.zd};e.Ch=function(){return this.e.Y};
e.yh=function(a){var b=arguments,c=b.length;if(0==c)return null;for(var d=0;d<c;++d){var f=this.e,g=b[d],h=Object.getPrototypeOf(f),k=h.xf;k||(k=[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],h.xf=k);h=qf(g,f,f.Bd,k,f.Zg);++f.Zg;
f.zd<h&&(f.zd=h);rf(g,f.i[14],1==f.i[11])}return b[0]};e.Fh=function(a){for(var b=arguments.length,c=0;c<b;++c);return!1};e.xh=function(a,b){var c=this.e;c.ac[a]=b;c.$c=null};e.Gh=function(a){var b=this.e;b.ac=a||{};b.$c=null};e.Bh=function(){return this.e.Ad()};e.zh=function(){return this.e.Xf()};e.Hh=function(a){vf(this.e,!!a)};e.Dh=function(a){this.e.qb(a)};e.Eh=function(a){this.e.$b(a)};Object.defineProperties($.prototype,{duration:{get:$.prototype.Ah},position:{get:$.prototype.Ch}});
t("createjs.MovieClip.Timeline",$,{addTween:$.prototype.yh,removeTween:$.prototype.Fh,addLabel:$.prototype.xh,setLabels:$.prototype.Gh,getLabels:$.prototype.Bh,getCurrentLabel:$.prototype.zh,setPaused:$.prototype.Hh,gotoAndPlay:$.prototype.Dh,gotoAndStop:$.prototype.Eh});Z.prototype.timeline=null;e=Z.prototype;e.ac=null;e.zd=0;e.$c=null;e.Bd=null;e.ld=!1;e.Zg=0;e.xf=null;function wf(a,b,c){vf(a,b);var d=1*c;if(d!==d&&(d=a.ac[c],null==d))return;d|=0;(b||1>=d||d!=a.Y)&&Uc(a,d)}e.Ih=function(){return this.Y};
function vf(a,b){var c=!!b,d=Vc();c?Sc(a,d):Rc(a,d)}e.Jh=function(){vf(this,!1)};e.Kh=function(){vf(this,!0)};e.qb=function(a){wf(this,!1,a)};e.$b=function(a){wf(this,!0,a)};e.Ad=function(){if(!this.$c){var a=[],b;for(b in this.ac)a.push(new tf(b,this.ac[b]));a.sort(uf);this.$c=a}return this.$c};e.Xf=function(){var a=this.Ad(),b=a.length,c=a[0],d=this.Y;if(0==b||d<c.position)return"";for(var f=1;f<b;++f)if(c=a[f],d<c.position){c=a[f-1];break}return c.label};
e.na=function(a){Pc(this);Z.B.na.call(this,a)};e.Sb=function(a){if(this.ld){if(this.T){for(var b=this.T,c=this.i[14],d=this.i[10],f=1==this.i[11],g=Hc(b),h=g.length-1;0<=h;--h)rf(g[h],c,f);b.e=d}this.ld=!1}Z.B.Sb.call(this,a);if(a=this.Bd){b=a.length;for(c=0;c<b;++c)a[c].Lb||this.addChild(a[c]);this.Bd=[]}};
e.ya=function(a,b,c){if(b&1024){var d=a.e[10]|0;0<=d&&this.i[10]!=d&&(this.i[10]=d,this.ld=!0)}b&16384&&(d=a.e[14],this.i[14]!=d&&(this.i[14]=d,this.ld=!0));b&2048&&(d=a.e[11],this.i[11]!=d&&(this.i[11]=d,c&&Wc(c,this,2==d),this.ld=!0));Z.B.ya.call(this,a,b,c)};Object.defineProperties(Z.prototype,{currentFrame:{get:Z.prototype.Ih}});t("createjs.MovieClip",Z,{play:Z.prototype.Jh,stop:Z.prototype.Kh,gotoAndPlay:Z.prototype.qb,gotoAndStop:Z.prototype.$b,getLabels:Z.prototype.Ad,getCurrentLabel:Z.prototype.Xf});})();

